const fs = require('fs');

const TARGET_COUNTRIES = [
    'TR', 'US', 'DE', 'FR', 'GB', 'IT', 'ES', 'RU', 'CN', 'BR', 'IN', 'AU', 'JP', 'CA', 'MX', 'KR'
];

try {
    const rawData = fs.readFileSync('temp_world.json', 'utf8');
    const geojson = JSON.parse(rawData);

    // Get ALL countries, no filtering
    const features = geojson.features
        .filter(f => {
            const iso = f.properties.ISO_A2 || f.properties.iso_a2;
            return iso && iso !== '-99';
        })
        .map(f => ({
            type: 'Feature',
            id: (f.properties.ISO_A2 || f.properties.iso_a2).toLowerCase() === 'gb' ? 'uk' : (f.properties.ISO_A2 || f.properties.iso_a2).toLowerCase(),
            properties: { name: f.properties.NAME || f.properties.name },
            geometry: f.geometry
        }));

    const output = `// Optimized 110m Natural Earth Data
// Generated by process-map.js

export interface GeoJSONFeature {
    type: 'Feature';
    id: string;
    properties: {
        name: string;
    };
    geometry: {
        type: 'Polygon' | 'MultiPolygon';
        coordinates: number[][][] | number[][][][];
    };
}

export const WORLD_GEOJSON: { type: 'FeatureCollection'; features: GeoJSONFeature[] } = {
    type: 'FeatureCollection',
    features: ${JSON.stringify(features, null, 4)}
};
`;

    fs.writeFileSync('src/components/map/worldGeoJson.ts', output);
    console.log(`Successfully wrote ${features.length} countries to src/components/map/worldGeoJson.ts`);

} catch (e) {
    console.error('Error processing map:', e);
}
