import 'dotenv/config';
import { db } from '../config/db.js';
import { categories, rss_sources } from '../db/schema/index.js';

async function seed() {
    console.log('🌱 Seeding database...');

    // Insert categories (skip if already exists)
    await db.insert(categories).values([
        { id: 1, name: 'Politika', slug: 'politika', icon: '🏛️', color: '#3B82F6' },
        { id: 2, name: 'Ekonomi', slug: 'ekonomi', icon: '💰', color: '#10B981' },
        { id: 3, name: 'Spor', slug: 'spor', icon: '⚽', color: '#F59E0B' },
        { id: 4, name: 'Teknoloji', slug: 'teknoloji', icon: '💻', color: '#8B5CF6' },
        { id: 5, name: 'Sağlık', slug: 'saglik', icon: '🏥', color: '#EF4444' },
        { id: 6, name: 'Bilim', slug: 'bilim', icon: '🔬', color: '#06B6D4' },
        { id: 7, name: 'Kültür', slug: 'kultur', icon: '🎭', color: '#EC4899' },
        { id: 8, name: 'Dünya', slug: 'dunya', icon: '🌍', color: '#14B8A6' },
    ]).onConflictDoNothing();
    console.log('✅ Categories seeded (or already exist)');

    // Insert RSS sources with government alignment data
    await db.insert(rss_sources).values([
        // Turkey
        {
            id: 1,
            countryCode: 'tr',
            sourceName: 'Hürriyet',
            sourceLogoUrl: 'https://logo.clearbit.com/hurriyet.com.tr',
            rssUrl: 'https://www.hurriyet.com.tr/rss/anasayfa',
            isActive: true,
            biasScoreSystem: 5.5,
            govAlignmentScore: -1,
            govAlignmentLabel: 'Muhalefete Eğilimli',
            govAlignmentConfidence: 0.72,
            govAlignmentNotes: 'DYH grubu, editoryal çizgide iktidar politikalarına eleştirel vurgular daha sık.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 2,
            countryCode: 'tr',
            sourceName: 'Sözcü',
            sourceLogoUrl: 'https://logo.clearbit.com/sozcu.com.tr',
            rssUrl: 'https://www.sozcu.com.tr/feed/',
            isActive: true,
            biasScoreSystem: 4.0,
            govAlignmentScore: -4,
            govAlignmentLabel: 'Muhalefete Yakın',
            govAlignmentConfidence: 0.85,
            govAlignmentNotes: 'Güçlü muhalefet yanlısı editoryal çizgi.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 3,
            countryCode: 'tr',
            sourceName: 'NTV',
            sourceLogoUrl: 'https://logo.clearbit.com/ntv.com.tr',
            rssUrl: 'https://www.ntv.com.tr/gundem.rss',
            isActive: true,
            biasScoreSystem: 6.5,
            govAlignmentScore: 0,
            govAlignmentLabel: 'Karışık / Merkez',
            govAlignmentConfidence: 0.68,
            govAlignmentNotes: 'Görece dengeli yayın politikası.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 4,
            countryCode: 'tr',
            sourceName: 'Sabah',
            sourceLogoUrl: 'https://logo.clearbit.com/sabah.com.tr',
            rssUrl: 'https://www.sabah.com.tr/rss/anasayfa.xml',
            isActive: true,
            biasScoreSystem: 3.0,
            govAlignmentScore: 4,
            govAlignmentLabel: 'İktidara Yakın',
            govAlignmentConfidence: 0.88,
            govAlignmentNotes: 'Turkuaz medya grubu, iktidar yanlısı editoryal çizgi.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 5,
            countryCode: 'tr',
            sourceName: 'Cumhuriyet',
            sourceLogoUrl: 'https://logo.clearbit.com/cumhuriyet.com.tr',
            rssUrl: 'https://www.cumhuriyet.com.tr/rss',
            isActive: true,
            biasScoreSystem: 4.0,
            govAlignmentScore: -4,
            govAlignmentLabel: 'Muhalefete Yakın',
            govAlignmentConfidence: 0.90,
            govAlignmentNotes: 'Sol/laik çizgi, güçlü muhalefet yanlısı.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 6,
            countryCode: 'tr',
            sourceName: 'TRT Haber',
            sourceLogoUrl: 'https://logo.clearbit.com/trthaber.com',
            rssUrl: 'https://www.trthaber.com/sondakika.rss',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 4,
            govAlignmentLabel: 'İktidara Yakın',
            govAlignmentConfidence: 0.95,
            govAlignmentNotes: 'Resmi yayın kuruluşu.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 7,
            countryCode: 'tr',
            sourceName: 'CNN Türk',
            sourceLogoUrl: 'https://logo.clearbit.com/cnnturk.com',
            rssUrl: 'https://www.cnnturk.com/feed/rss/all/news',
            isActive: true,
            biasScoreSystem: 5.5,
            govAlignmentScore: 1,
            govAlignmentLabel: 'İktidara Eğilimli',
            govAlignmentConfidence: 0.70,
            govAlignmentNotes: 'Demirören medya grubu, merkez-sağ çizgi.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 8,
            countryCode: 'tr',
            sourceName: 'Milliyet',
            sourceLogoUrl: 'https://logo.clearbit.com/milliyet.com.tr',
            rssUrl: 'https://www.milliyet.com.tr/rss/rssNew/gundemRss.xml',
            isActive: true,
            biasScoreSystem: 5.5,
            govAlignmentScore: 1,
            govAlignmentLabel: 'İktidara Eğilimli',
            govAlignmentConfidence: 0.72,
            govAlignmentNotes: 'Demirören medya grubu.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 33,
            countryCode: 'tr',
            sourceName: 'Haberturk RSS',
            sourceLogoUrl: 'https://logo.clearbit.com/haberturk.com',
            rssUrl: 'https://haberturk.com/rss',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 34,
            countryCode: 'tr',
            sourceName: 'Haberturk Ekonomi',
            sourceLogoUrl: 'https://logo.clearbit.com/haberturk.com',
            rssUrl: 'https://haberturk.com/rss/ekonomi.xml',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 35,
            countryCode: 'tr',
            sourceName: 'Haberturk Gundem',
            sourceLogoUrl: 'https://logo.clearbit.com/haberturk.com',
            rssUrl: 'https://haberturk.com/rss/kategori/gundem.xml',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 36,
            countryCode: 'tr',
            sourceName: 'Haberler.com',
            sourceLogoUrl: 'https://logo.clearbit.com/haberler.com',
            rssUrl: 'https://rss.haberler.com/rss.asp',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 37,
            countryCode: 'tr',
            sourceName: 'Haber7',
            sourceLogoUrl: 'https://logo.clearbit.com/haber7.com',
            rssUrl: 'https://i12.haber7.net/sondakika/news.xml',
            isActive: true,
            biasScoreSystem: 4.0,
            govAlignmentScore: 2,
            govAlignmentLabel: 'Hafif Olumlu',
            govAlignmentConfidence: 0.6,
        },
        {
            id: 38,
            countryCode: 'tr',
            sourceName: 'Vatan',
            sourceLogoUrl: 'https://logo.clearbit.com/gazetevatan.com',
            rssUrl: 'https://gazetevatan.com/rss/gundem.xml',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 1,
            govAlignmentConfidence: 0.6,
        },
        {
            id: 39,
            countryCode: 'tr',
            sourceName: 'SoL Haber',
            sourceLogoUrl: 'https://logo.clearbit.com/sol.org.tr',
            rssUrl: 'https://haber.sol.org.tr/rss.xml',
            isActive: true,
            biasScoreSystem: 3.0,
            govAlignmentScore: -5,
            govAlignmentLabel: 'Hükümete Eleştirel',
            govAlignmentConfidence: 0.8,
        },

        // Germany
        {
            id: 9,
            countryCode: 'de',
            sourceName: 'Der Spiegel',
            sourceLogoUrl: 'https://via.placeholder.com/100x100?text=Spiegel',
            rssUrl: 'https://www.spiegel.de/schlagzeilen/index.rss',
            isActive: true,
            biasScoreSystem: 7.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 10,
            countryCode: 'de',
            sourceName: 'Bild',
            sourceLogoUrl: 'https://via.placeholder.com/100x100?text=Bild',
            rssUrl: 'https://www.bild.de/rssfeeds/vw-alles/vw-alles-26970192,sort=1,view=rss2.bild.xml',
            isActive: true,
            biasScoreSystem: 4.5,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 24,
            countryCode: 'de',
            sourceName: 'Zeit Politics',
            sourceLogoUrl: 'https://logo.clearbit.com/zeit.de',
            rssUrl: 'https://newsfeed.zeit.de/politik/index',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 25,
            countryCode: 'de',
            sourceName: 'The Local DE',
            sourceLogoUrl: 'https://logo.clearbit.com/thelocal.de',
            rssUrl: 'https://feeds.thelocal.com/rss/de',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 26,
            countryCode: 'de',
            sourceName: 'Tagesschau',
            sourceLogoUrl: 'https://logo.clearbit.com/tagesschau.de',
            rssUrl: 'https://www.tagesschau.de/xml/rss2/',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 27,
            countryCode: 'de',
            sourceName: 'FAZ',
            sourceLogoUrl: 'https://logo.clearbit.com/faz.net',
            rssUrl: 'https://faz.net/rss/aktuell',
            isActive: true,
            biasScoreSystem: 6.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 28,
            countryCode: 'de',
            sourceName: 'DW Top',
            sourceLogoUrl: 'https://logo.clearbit.com/dw.com',
            rssUrl: 'https://rss.dw.com/rdf/rss-en-top',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 29,
            countryCode: 'de',
            sourceName: 'DW All',
            sourceLogoUrl: 'https://logo.clearbit.com/dw.com',
            rssUrl: 'https://rss.dw.com/rdf/rss-en-all',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },

        // USA
        {
            id: 11,
            countryCode: 'us',
            sourceName: 'CNN',
            sourceLogoUrl: 'https://via.placeholder.com/100x100?text=CNN',
            rssUrl: 'http://rss.cnn.com/rss/edition.rss',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 12,
            countryCode: 'us',
            sourceName: 'Reuters',
            sourceLogoUrl: 'https://via.placeholder.com/100x100?text=Reuters',
            rssUrl: 'https://www.reutersagency.com/feed/',
            isActive: true,
            biasScoreSystem: 8.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 13,
            countryCode: 'us',
            sourceName: 'The Guardian',
            sourceLogoUrl: 'https://via.placeholder.com/100x100?text=Guardian',
            rssUrl: 'https://www.theguardian.com/world/rss',
            isActive: true,
            biasScoreSystem: 6.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 30,
            countryCode: 'us',
            sourceName: 'PBS Politics',
            sourceLogoUrl: 'https://logo.clearbit.com/pbs.org',
            rssUrl: 'https://www.pbs.org/newshour/politics/feed',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 31,
            countryCode: 'us',
            sourceName: 'Reuters Politics',
            sourceLogoUrl: 'https://logo.clearbit.com/reuters.com',
            rssUrl: 'https://feeds.reuters.com/Reuters/PoliticsNews',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },

        // UK
        {
            id: 14,
            countryCode: 'uk',
            sourceName: 'Politics.co.uk',
            sourceLogoUrl: 'https://logo.clearbit.com/politics.co.uk',
            rssUrl: 'https://politics.co.uk/feed',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 15,
            countryCode: 'uk',
            sourceName: 'BBC Business',
            sourceLogoUrl: 'https://logo.clearbit.com/bbc.co.uk',
            rssUrl: 'https://feeds.bbci.co.uk/news/business/rss.xml',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 16,
            countryCode: 'uk',
            sourceName: 'BBC News',
            sourceLogoUrl: 'https://logo.clearbit.com/bbc.co.uk',
            rssUrl: 'https://feeds.bbci.co.uk/news/rss.xml',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },

        // France
        {
            id: 17,
            countryCode: 'fr',
            sourceName: 'France TV Politics',
            sourceLogoUrl: 'https://logo.clearbit.com/francetvinfo.fr',
            rssUrl: 'https://francetvinfo.fr/politique.rss',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 18,
            countryCode: 'fr',
            sourceName: 'France TV Economy',
            sourceLogoUrl: 'https://logo.clearbit.com/francetvinfo.fr',
            rssUrl: 'https://francetvinfo.fr/economie.rss',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },

        // Italy
        {
            id: 19,
            countryCode: 'it',
            sourceName: 'Corriere Politica',
            sourceLogoUrl: 'https://logo.clearbit.com/corriere.it',
            rssUrl: 'https://corriere.it/dynamic-feed/rss/politica',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 20,
            countryCode: 'it',
            sourceName: 'Corriere Economia',
            sourceLogoUrl: 'https://logo.clearbit.com/corriere.it',
            rssUrl: 'https://corriere.it/dynamic-feed/rss/economia',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },

        // Spain
        {
            id: 21,
            countryCode: 'es',
            sourceName: 'El Mundo',
            sourceLogoUrl: 'https://logo.clearbit.com/elmundo.es',
            rssUrl: 'https://e00-elmundo.uecdn.es/rss/portada.xml',
            isActive: true,
            biasScoreSystem: 6.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 22,
            countryCode: 'es',
            sourceName: 'El Diario',
            sourceLogoUrl: 'https://logo.clearbit.com/eldiario.es',
            rssUrl: 'https://eldiario.es/rss',
            isActive: true,
            biasScoreSystem: 4.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 23,
            countryCode: 'es',
            sourceName: 'El Espanol',
            sourceLogoUrl: 'https://logo.clearbit.com/elespanol.com',
            rssUrl: 'https://elespanal.com/rss/espana',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },

        // Russia
        {
            id: 32,
            countryCode: 'ru',
            sourceName: 'Sputnik Globe',
            sourceLogoUrl: 'https://logo.clearbit.com/sputnikglobe.com',
            rssUrl: 'https://sputnikglobe.com/export/rss2/russia',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
    ]).onConflictDoNothing();
    console.log('✅ RSS sources seeded (or already exist)');

    console.log('🎉 Seeding completed!');
}

seed()
    .catch((error) => {
        console.error('❌ Seeding failed:', error);
        process.exit(1);
    })
    .then(() => {
        process.exit(0);
    });
