import { db } from '../config/db.js';
import { twitter_accounts } from '../db/schema/index.js';

async function seedTwitter() {
    console.log('🐦 Seeding Twitter accounts...');

    await db.insert(twitter_accounts).values([
        // ===================== TURKEY (TR) =====================
        { id: 1, countryCode: 'tr', userName: 'RTErdogan', displayName: 'Recep Tayyip Erdogan', accountType: 'government' as const, description: 'Cumhurbaskani' },
        { id: 2, countryCode: 'tr', userName: 'tcbaskanlik', displayName: 'T.C. Cumhurbaskanligi', accountType: 'government' as const, description: 'Cumhurbaskanligi resmi hesabi' },
        { id: 3, countryCode: 'tr', userName: 'TC_Disisleri', displayName: 'TC Disisleri Bakanligi', accountType: 'government' as const, description: 'Disisleri Bakanligi' },
        { id: 4, countryCode: 'tr', userName: 'iletisim', displayName: 'Iletisim Baskanligi', accountType: 'government' as const, description: 'Cumhurbaskanligi Iletisim Baskanligi' },
        { id: 5, countryCode: 'tr', userName: 'tcbestepe', displayName: 'T.C. Cumhurbaskanligi', accountType: 'government' as const, description: 'Cumhurbaskanligi resmi hesabi (alternatif)' },

        // ===================== GERMANY (DE) =====================
        { id: 8, countryCode: 'de', userName: 'Bundeskanzler', displayName: 'Bundeskanzler', accountType: 'government' as const, description: 'Federal Chancellor' },
        { id: 9, countryCode: 'de', userName: 'AuswaertigesAmt', displayName: 'Auswaertiges Amt', accountType: 'government' as const, description: 'Federal Foreign Office' },
        { id: 10, countryCode: 'de', userName: 'RegSprecher', displayName: 'Regierungssprecher', accountType: 'government' as const, description: 'Government Spokesperson' },
        { id: 200, countryCode: 'de', userName: 'BMVg_Bundeswehr', displayName: 'Bundesverteidigungsministerium', accountType: 'government' as const, description: 'Federal Ministry of Defence' },
        { id: 201, countryCode: 'de', userName: 'BMF_Bund', displayName: 'Bundesfinanzministerium', accountType: 'government' as const, description: 'Federal Ministry of Finance' },
        { id: 202, countryCode: 'de', userName: 'BMI_Bund', displayName: 'Bundesinnenministerium', accountType: 'government' as const, description: 'Federal Ministry of the Interior' },
        { id: 203, countryCode: 'de', userName: 'Bundestag', displayName: 'Deutscher Bundestag', accountType: 'government' as const, description: 'German Federal Parliament' },
        { id: 11, countryCode: 'de', userName: 'tagesschau', displayName: 'tagesschau', accountType: 'news_agency' as const, description: 'ARD public news' },
        { id: 12, countryCode: 'de', userName: 'ZDFheute', displayName: 'ZDFheute', accountType: 'news_agency' as const, description: 'ZDF public broadcaster' },
        { id: 13, countryCode: 'de', userName: 'dpa', displayName: 'dpa', accountType: 'news_agency' as const, description: 'Deutsche Presse-Agentur' },
        { id: 204, countryCode: 'de', userName: 'derspiegel', displayName: 'DER SPIEGEL', accountType: 'news_agency' as const, description: 'Der Spiegel magazine' },
        { id: 205, countryCode: 'de', userName: 'BILD', displayName: 'BILD', accountType: 'news_agency' as const, description: 'Bild newspaper' },
        { id: 206, countryCode: 'de', userName: 'faznet', displayName: 'FAZ', accountType: 'news_agency' as const, description: 'Frankfurter Allgemeine Zeitung' },
        { id: 207, countryCode: 'de', userName: 'SZ_TopNews', displayName: 'Sueddeutsche Zeitung', accountType: 'news_agency' as const, description: 'Sueddeutsche Zeitung' },
        { id: 208, countryCode: 'de', userName: 'welt', displayName: 'WELT', accountType: 'news_agency' as const, description: 'Die Welt newspaper' },
        { id: 209, countryCode: 'de', userName: 'ntvde', displayName: 'ntv Nachrichten', accountType: 'news_agency' as const, description: 'ntv news channel' },
        { id: 210, countryCode: 'de', userName: 'sternonline', displayName: 'stern', accountType: 'news_agency' as const, description: 'Stern magazine' },
        { id: 212, countryCode: 'de', userName: 'nicolediekmann', displayName: 'Nicole Diekmann', accountType: 'journalist' as const, description: 'ZDF journalist' },
        { id: 213, countryCode: 'de', userName: 'georgrestle', displayName: 'Georg Restle', accountType: 'journalist' as const, description: 'ARD Monitor presenter' },
        { id: 214, countryCode: 'de', userName: 'robinalexander_', displayName: 'Robin Alexander', accountType: 'journalist' as const, description: 'WELT journalist' },
        { id: 215, countryCode: 'de', userName: 'TiloJung', displayName: 'Tilo Jung', accountType: 'journalist' as const, description: 'Jung und Naiv' },
        { id: 216, countryCode: 'de', userName: 'ronzheimer', displayName: 'Paul Ronzheimer', accountType: 'journalist' as const, description: 'BILD journalist' },
        { id: 217, countryCode: 'de', userName: 'spdde', displayName: 'SPD', accountType: 'political_party' as const, description: 'Social Democratic Party' },
        { id: 218, countryCode: 'de', userName: 'CDU', displayName: 'CDU', accountType: 'political_party' as const, description: 'Christian Democratic Union' },
        { id: 219, countryCode: 'de', userName: 'CSU', displayName: 'CSU', accountType: 'political_party' as const, description: 'Christian Social Union' },
        { id: 220, countryCode: 'de', userName: 'Die_Gruenen', displayName: 'Buendnis 90/Die Gruenen', accountType: 'political_party' as const, description: 'The Greens' },
        { id: 221, countryCode: 'de', userName: 'fdp', displayName: 'FDP', accountType: 'political_party' as const, description: 'Free Democratic Party' },
        { id: 222, countryCode: 'de', userName: 'AfD', displayName: 'AfD', accountType: 'political_party' as const, description: 'Alternative for Germany' },
        { id: 223, countryCode: 'de', userName: 'dieLinke', displayName: 'Die Linke', accountType: 'political_party' as const, description: 'The Left party' },
        { id: 224, countryCode: 'de', userName: '_FriedrichMerz', displayName: 'Friedrich Merz', accountType: 'political_party' as const, description: 'CDU leader, Chancellor' },
        { id: 225, countryCode: 'de', userName: 'c_lindner', displayName: 'Christian Lindner', accountType: 'political_party' as const, description: 'FDP leader' },
        { id: 226, countryCode: 'de', userName: 'SWagenknecht', displayName: 'Sahra Wagenknecht', accountType: 'political_party' as const, description: 'BSW leader' },
        { id: 227, countryCode: 'de', userName: 'bundesbank', displayName: 'Deutsche Bundesbank', accountType: 'institution' as const, description: 'German Federal Bank' },
        { id: 228, countryCode: 'de', userName: 'DFB', displayName: 'DFB', accountType: 'institution' as const, description: 'German Football Association' },
        { id: 229, countryCode: 'de', userName: 'FCBayern', displayName: 'FC Bayern', accountType: 'institution' as const, description: 'FC Bayern Munich' },
        { id: 230, countryCode: 'de', userName: 'BVB', displayName: 'Borussia Dortmund', accountType: 'institution' as const, description: 'BVB Dortmund' },

        // ===================== UNITED STATES (US) =====================
        { id: 14, countryCode: 'us', userName: 'POTUS', displayName: 'President of the United States', accountType: 'government' as const, description: 'US President official' },
        { id: 15, countryCode: 'us', userName: 'WhiteHouse', displayName: 'The White House', accountType: 'government' as const, description: 'White House official' },
        { id: 16, countryCode: 'us', userName: 'StateDept', displayName: 'Department of State', accountType: 'government' as const, description: 'US State Department' },
        { id: 240, countryCode: 'us', userName: 'VP', displayName: 'Vice President', accountType: 'government' as const, description: 'US Vice President official' },
        { id: 241, countryCode: 'us', userName: 'DeptofDefense', displayName: 'Department of Defense', accountType: 'government' as const, description: 'US Pentagon / DoD official' },
        { id: 242, countryCode: 'us', userName: 'USTreasury', displayName: 'U.S. Treasury', accountType: 'government' as const, description: 'US Department of the Treasury' },
        { id: 243, countryCode: 'us', userName: 'SpeakerJohnson', displayName: 'Speaker Mike Johnson', accountType: 'government' as const, description: 'Speaker of the US House' },
        { id: 17, countryCode: 'us', userName: 'AP', displayName: 'The Associated Press', accountType: 'news_agency' as const, description: 'AP wire service' },
        { id: 18, countryCode: 'us', userName: 'Reuters', displayName: 'Reuters', accountType: 'news_agency' as const, description: 'Reuters news wire' },
        { id: 19, countryCode: 'us', userName: 'ABC', displayName: 'ABC News', accountType: 'news_agency' as const, description: 'ABC News' },
        { id: 244, countryCode: 'us', userName: 'CNN', displayName: 'CNN', accountType: 'news_agency' as const, description: 'CNN breaking news' },
        { id: 245, countryCode: 'us', userName: 'nytimes', displayName: 'The New York Times', accountType: 'news_agency' as const, description: 'New York Times' },
        { id: 246, countryCode: 'us', userName: 'washingtonpost', displayName: 'The Washington Post', accountType: 'news_agency' as const, description: 'Washington Post' },
        { id: 247, countryCode: 'us', userName: 'FoxNews', displayName: 'Fox News', accountType: 'news_agency' as const, description: 'Fox News' },
        { id: 248, countryCode: 'us', userName: 'NBCNews', displayName: 'NBC News', accountType: 'news_agency' as const, description: 'NBC News' },
        { id: 249, countryCode: 'us', userName: 'CBSNews', displayName: 'CBS News', accountType: 'news_agency' as const, description: 'CBS News' },
        { id: 250, countryCode: 'us', userName: 'Bloomberg', displayName: 'Bloomberg', accountType: 'news_agency' as const, description: 'Bloomberg News' },
        { id: 251, countryCode: 'us', userName: 'WSJ', displayName: 'The Wall Street Journal', accountType: 'news_agency' as const, description: 'Wall Street Journal' },
        { id: 252, countryCode: 'us', userName: 'NPR', displayName: 'NPR', accountType: 'news_agency' as const, description: 'National Public Radio' },
        { id: 253, countryCode: 'us', userName: 'PBS', displayName: 'PBS', accountType: 'news_agency' as const, description: 'Public Broadcasting Service' },
        { id: 254, countryCode: 'us', userName: 'andersoncooper', displayName: 'Anderson Cooper', accountType: 'journalist' as const, description: 'CNN anchor' },
        { id: 255, countryCode: 'us', userName: 'maggieNYT', displayName: 'Maggie Haberman', accountType: 'journalist' as const, description: 'NYT White House correspondent' },
        { id: 256, countryCode: 'us', userName: 'JonLemire', displayName: 'Jonathan Lemire', accountType: 'journalist' as const, description: 'MSNBC anchor, Politico' },
        { id: 257, countryCode: 'us', userName: 'PeterAlexander', displayName: 'Peter Alexander', accountType: 'journalist' as const, description: 'NBC News correspondent' },
        { id: 258, countryCode: 'us', userName: 'SenSchumer', displayName: 'Chuck Schumer', accountType: 'political_party' as const, description: 'Senate Democratic Leader' },
        { id: 259, countryCode: 'us', userName: 'SenJohnThune', displayName: 'John Thune', accountType: 'political_party' as const, description: 'Senate Republican Leader' },
        { id: 260, countryCode: 'us', userName: 'RepJeffries', displayName: 'Hakeem Jeffries', accountType: 'political_party' as const, description: 'House Democratic Leader' },
        { id: 261, countryCode: 'us', userName: 'SenTedCruz', displayName: 'Ted Cruz', accountType: 'political_party' as const, description: 'US Senator from Texas' },
        { id: 262, countryCode: 'us', userName: 'SenWarren', displayName: 'Elizabeth Warren', accountType: 'political_party' as const, description: 'US Senator from Massachusetts' },
        { id: 263, countryCode: 'us', userName: 'LindseyGrahamSC', displayName: 'Lindsey Graham', accountType: 'political_party' as const, description: 'US Senator from South Carolina' },
        { id: 264, countryCode: 'us', userName: 'FederalReserve', displayName: 'Federal Reserve', accountType: 'institution' as const, description: 'US Federal Reserve System' },
        { id: 265, countryCode: 'us', userName: 'SECGov', displayName: 'U.S. SEC', accountType: 'institution' as const, description: 'Securities and Exchange Commission' },
        { id: 266, countryCode: 'us', userName: 'FBI', displayName: 'FBI', accountType: 'institution' as const, description: 'Federal Bureau of Investigation' },
        { id: 267, countryCode: 'us', userName: 'CIA', displayName: 'CIA', accountType: 'institution' as const, description: 'Central Intelligence Agency' },

        // ===================== UNITED KINGDOM (UK) =====================
        { id: 20, countryCode: 'uk', userName: 'UKPrimeMinister', displayName: 'UK Prime Minister', accountType: 'government' as const, description: 'PM official' },
        { id: 21, countryCode: 'uk', userName: '10DowningStreet', displayName: '10 Downing Street', accountType: 'government' as const, description: 'PM office' },
        { id: 22, countryCode: 'uk', userName: 'FCDOGovUK', displayName: 'FCDO', accountType: 'government' as const, description: 'Foreign Commonwealth & Development Office' },
        { id: 280, countryCode: 'uk', userName: 'HMTreasury', displayName: 'HM Treasury', accountType: 'government' as const, description: 'UK Treasury official' },
        { id: 281, countryCode: 'uk', userName: 'HomeOffice', displayName: 'Home Office', accountType: 'government' as const, description: 'Home Office official' },
        { id: 282, countryCode: 'uk', userName: 'UKParliament', displayName: 'UK Parliament', accountType: 'government' as const, description: 'UK Parliament official' },
        { id: 283, countryCode: 'uk', userName: 'HouseofCommons', displayName: 'House of Commons', accountType: 'government' as const, description: 'House of Commons official' },
        { id: 23, countryCode: 'uk', userName: 'BBCNews', displayName: 'BBC News', accountType: 'news_agency' as const, description: 'BBC News (World)' },
        { id: 24, countryCode: 'uk', userName: 'SkyNews', displayName: 'Sky News', accountType: 'news_agency' as const, description: 'Sky News' },
        { id: 284, countryCode: 'uk', userName: 'guardian', displayName: 'The Guardian', accountType: 'news_agency' as const, description: 'The Guardian newspaper' },
        { id: 285, countryCode: 'uk', userName: 'Telegraph', displayName: 'The Telegraph', accountType: 'news_agency' as const, description: 'The Daily Telegraph' },
        { id: 286, countryCode: 'uk', userName: 'TheTimes', displayName: 'The Times', accountType: 'news_agency' as const, description: 'The Times newspaper' },
        { id: 287, countryCode: 'uk', userName: 'FT', displayName: 'Financial Times', accountType: 'news_agency' as const, description: 'Financial Times' },
        { id: 288, countryCode: 'uk', userName: 'Independent', displayName: 'The Independent', accountType: 'news_agency' as const, description: 'The Independent newspaper' },
        { id: 289, countryCode: 'uk', userName: 'itvnews', displayName: 'ITV News', accountType: 'news_agency' as const, description: 'ITV News' },
        { id: 290, countryCode: 'uk', userName: 'Channel4News', displayName: 'Channel 4 News', accountType: 'news_agency' as const, description: 'Channel 4 News' },
        { id: 291, countryCode: 'uk', userName: 'BBCPolitics', displayName: 'BBC Politics', accountType: 'news_agency' as const, description: 'BBC Politics coverage' },
        { id: 292, countryCode: 'uk', userName: 'LBC', displayName: 'LBC', accountType: 'news_agency' as const, description: 'LBC radio news' },
        { id: 293, countryCode: 'uk', userName: 'BBCLauraK', displayName: 'Laura Kuenssberg', accountType: 'journalist' as const, description: 'BBC presenter' },
        { id: 294, countryCode: 'uk', userName: 'BethRigby', displayName: 'Beth Rigby', accountType: 'journalist' as const, description: 'Sky News Political Editor' },
        { id: 295, countryCode: 'uk', userName: 'PestonITV', displayName: 'Robert Peston', accountType: 'journalist' as const, description: 'ITV Political Editor' },
        { id: 296, countryCode: 'uk', userName: 'PippaCrerar', displayName: 'Pippa Crerar', accountType: 'journalist' as const, description: 'Guardian Political Editor' },
        { id: 297, countryCode: 'uk', userName: 'MrHarryCole', displayName: 'Harry Cole', accountType: 'journalist' as const, description: 'The Sun Political Editor' },
        { id: 298, countryCode: 'uk', userName: 'KeirStarmer', displayName: 'Keir Starmer', accountType: 'political_party' as const, description: 'PM, Labour Party leader' },
        { id: 299, countryCode: 'uk', userName: 'UKLabour', displayName: 'The Labour Party', accountType: 'political_party' as const, description: 'Labour Party official' },
        { id: 300, countryCode: 'uk', userName: 'Conservatives', displayName: 'Conservatives', accountType: 'political_party' as const, description: 'Conservative Party official' },
        { id: 301, countryCode: 'uk', userName: 'KemiBadenoch', displayName: 'Kemi Badenoch', accountType: 'political_party' as const, description: 'Conservative Party leader' },
        { id: 302, countryCode: 'uk', userName: 'theSNP', displayName: 'The SNP', accountType: 'political_party' as const, description: 'Scottish National Party' },
        { id: 303, countryCode: 'uk', userName: 'LibDems', displayName: 'Liberal Democrats', accountType: 'political_party' as const, description: 'Liberal Democrats official' },
        { id: 304, countryCode: 'uk', userName: 'ReformParty_UK', displayName: 'Reform UK', accountType: 'political_party' as const, description: 'Reform UK party official' },
        { id: 305, countryCode: 'uk', userName: 'Nigel_Farage', displayName: 'Nigel Farage', accountType: 'political_party' as const, description: 'Reform UK leader' },
        { id: 306, countryCode: 'uk', userName: 'bankofengland', displayName: 'Bank of England', accountType: 'institution' as const, description: 'Bank of England official' },
        { id: 307, countryCode: 'uk', userName: 'NHSEngland', displayName: 'NHS England', accountType: 'institution' as const, description: 'NHS England official' },
        { id: 308, countryCode: 'uk', userName: 'DefenceHQ', displayName: 'Ministry of Defence', accountType: 'institution' as const, description: 'UK Ministry of Defence' },

        // ===================== FRANCE (FR) =====================
        { id: 25, countryCode: 'fr', userName: 'EmmanuelMacron', displayName: 'Emmanuel Macron', accountType: 'government' as const, description: 'President of France' },
        { id: 26, countryCode: 'fr', userName: 'Elysee', displayName: 'Elysee', accountType: 'government' as const, description: 'French Presidency' },
        { id: 27, countryCode: 'fr', userName: 'francediplo', displayName: 'France Diplomatie', accountType: 'government' as const, description: 'Ministry of Foreign Affairs' },
        { id: 28, countryCode: 'fr', userName: 'gouvernementFR', displayName: 'Gouvernement', accountType: 'government' as const, description: 'French Government' },
        { id: 320, countryCode: 'fr', userName: 'AsssembleeNat', displayName: 'Assemblee nationale', accountType: 'government' as const, description: 'French National Assembly' },
        { id: 321, countryCode: 'fr', userName: 'Senat', displayName: 'Senat', accountType: 'government' as const, description: 'French Senate' },
        { id: 322, countryCode: 'fr', userName: 'FBayrou', displayName: 'Francois Bayrou', accountType: 'government' as const, description: 'Prime Minister of France' },
        { id: 323, countryCode: 'fr', userName: 'MinArmees', displayName: 'Ministere des Armees', accountType: 'government' as const, description: 'Ministry of Armed Forces' },
        { id: 29, countryCode: 'fr', userName: 'AFP', displayName: 'AFP', accountType: 'news_agency' as const, description: 'Agence France-Presse' },
        { id: 30, countryCode: 'fr', userName: 'lemondefr', displayName: 'Le Monde', accountType: 'news_agency' as const, description: 'Le Monde newspaper' },
        { id: 324, countryCode: 'fr', userName: 'Le_Figaro', displayName: 'Le Figaro', accountType: 'news_agency' as const, description: 'Le Figaro newspaper' },
        { id: 326, countryCode: 'fr', userName: 'France24_fr', displayName: 'France 24', accountType: 'news_agency' as const, description: 'France 24 French' },
        { id: 327, countryCode: 'fr', userName: 'BFMTV', displayName: 'BFM TV', accountType: 'news_agency' as const, description: 'BFM TV news channel' },
        { id: 328, countryCode: 'fr', userName: 'LCI', displayName: 'LCI', accountType: 'news_agency' as const, description: 'LCI news channel' },
        { id: 329, countryCode: 'fr', userName: 'Mediapart', displayName: 'Mediapart', accountType: 'news_agency' as const, description: 'Mediapart investigative' },
        { id: 330, countryCode: 'fr', userName: 'LExpress', displayName: 'L Express', accountType: 'news_agency' as const, description: 'L Express magazine' },
        { id: 332, countryCode: 'fr', userName: 'MLP_officiel', displayName: 'Marine Le Pen', accountType: 'political_party' as const, description: 'RN, former presidential candidate' },
        { id: 333, countryCode: 'fr', userName: 'J_Bardella', displayName: 'Jordan Bardella', accountType: 'political_party' as const, description: 'RN president' },
        { id: 334, countryCode: 'fr', userName: 'RNational_off', displayName: 'Rassemblement National', accountType: 'political_party' as const, description: 'National Rally party' },
        { id: 335, countryCode: 'fr', userName: 'JLMelenchon', displayName: 'Jean-Luc Melenchon', accountType: 'political_party' as const, description: 'La France Insoumise founder' },
        { id: 336, countryCode: 'fr', userName: 'FranceInsoumise', displayName: 'La France Insoumise', accountType: 'political_party' as const, description: 'LFI party official' },
        { id: 338, countryCode: 'fr', userName: 'lesRepublicains', displayName: 'Les Republicains', accountType: 'political_party' as const, description: 'Les Republicains party' },
        { id: 340, countryCode: 'fr', userName: 'FFF', displayName: 'FFF', accountType: 'institution' as const, description: 'French Football Federation' },

        // ===================== SPAIN (ES) =====================
        { id: 31, countryCode: 'es', userName: 'sanchezcastejon', displayName: 'Pedro Sanchez', accountType: 'government' as const, description: 'President of the Government' },
        { id: 32, countryCode: 'es', userName: 'desdelamoncloa', displayName: 'La Moncloa', accountType: 'government' as const, description: 'Spanish Government' },
        { id: 33, countryCode: 'es', userName: 'MAECgob', displayName: 'MAEC', accountType: 'government' as const, description: 'Ministry of Foreign Affairs' },
        { id: 360, countryCode: 'es', userName: 'guardiacivil', displayName: 'Guardia Civil', accountType: 'government' as const, description: 'Spanish Civil Guard' },
        { id: 361, countryCode: 'es', userName: 'policia', displayName: 'Policia Nacional', accountType: 'government' as const, description: 'National Police' },
        { id: 362, countryCode: 'es', userName: 'CasaReal', displayName: 'Casa Real', accountType: 'government' as const, description: 'Spanish Royal Household' },
        { id: 34, countryCode: 'es', userName: 'EFEnoticias', displayName: 'Agencia EFE', accountType: 'news_agency' as const, description: 'EFE national news agency' },
        { id: 35, countryCode: 'es', userName: 'el_pais', displayName: 'El Pais', accountType: 'news_agency' as const, description: 'El Pais newspaper' },
        { id: 363, countryCode: 'es', userName: 'elmundoes', displayName: 'El Mundo', accountType: 'news_agency' as const, description: 'El Mundo newspaper' },
        { id: 364, countryCode: 'es', userName: 'LaVanguardia', displayName: 'La Vanguardia', accountType: 'news_agency' as const, description: 'La Vanguardia newspaper' },
        { id: 365, countryCode: 'es', userName: 'abc_es', displayName: 'ABC', accountType: 'news_agency' as const, description: 'ABC newspaper' },
        { id: 366, countryCode: 'es', userName: 'rtve', displayName: 'RTVE', accountType: 'news_agency' as const, description: 'Public broadcaster' },
        { id: 367, countryCode: 'es', userName: '20m', displayName: '20 minutos', accountType: 'news_agency' as const, description: '20 minutos newspaper' },
        { id: 368, countryCode: 'es', userName: 'eldiarioes', displayName: 'eldiario.es', accountType: 'news_agency' as const, description: 'eldiario.es digital newspaper' },
        { id: 369, countryCode: 'es', userName: 'europapress', displayName: 'Europa Press', accountType: 'news_agency' as const, description: 'Europa Press news agency' },
        { id: 370, countryCode: 'es', userName: 'elconfidencial', displayName: 'El Confidencial', accountType: 'news_agency' as const, description: 'El Confidencial digital' },
        { id: 371, countryCode: 'es', userName: 'laSextaTV', displayName: 'laSexta', accountType: 'news_agency' as const, description: 'laSexta TV (Atresmedia)' },
        { id: 372, countryCode: 'es', userName: 'iescolar', displayName: 'Ignacio Escolar', accountType: 'journalist' as const, description: 'Founder of eldiario.es' },
        { id: 373, countryCode: 'es', userName: 'perezreverte', displayName: 'Arturo Perez-Reverte', accountType: 'journalist' as const, description: 'Novelist and commentator' },
        { id: 374, countryCode: 'es', userName: 'JordiEvole', displayName: 'Jordi Evole', accountType: 'journalist' as const, description: 'TV journalist (Salvados)' },
        { id: 375, countryCode: 'es', userName: 'pedrojramirez', displayName: 'Pedro J. Ramirez', accountType: 'journalist' as const, description: 'Founder of El Espanol' },
        { id: 376, countryCode: 'es', userName: 'julia_otero', displayName: 'Julia Otero', accountType: 'journalist' as const, description: 'Radio journalist (Onda Cero)' },
        { id: 377, countryCode: 'es', userName: 'ppopular', displayName: 'Partido Popular', accountType: 'political_party' as const, description: 'PP official' },
        { id: 378, countryCode: 'es', userName: 'NunezFeijoo', displayName: 'Alberto Nunez Feijoo', accountType: 'political_party' as const, description: 'PP leader' },
        { id: 379, countryCode: 'es', userName: 'vox_es', displayName: 'Vox', accountType: 'political_party' as const, description: 'Vox party' },
        { id: 380, countryCode: 'es', userName: 'Santi_ABASCAL', displayName: 'Santiago Abascal', accountType: 'political_party' as const, description: 'Vox leader' },
        { id: 381, countryCode: 'es', userName: 'PODEMOS', displayName: 'Podemos', accountType: 'political_party' as const, description: 'Podemos party' },
        { id: 382, countryCode: 'es', userName: 'PSOE', displayName: 'PSOE', accountType: 'political_party' as const, description: 'Spanish Socialist Workers Party' },
        { id: 383, countryCode: 'es', userName: 'Esquerra_ERC', displayName: 'Esquerra Republicana', accountType: 'political_party' as const, description: 'ERC Catalan republican party' },
        { id: 384, countryCode: 'es', userName: 'ehbildu', displayName: 'EH Bildu', accountType: 'political_party' as const, description: 'Basque left-wing coalition' },
        { id: 385, countryCode: 'es', userName: 'BancoDeEspana', displayName: 'Banco de Espana', accountType: 'institution' as const, description: 'Bank of Spain' },
        { id: 386, countryCode: 'es', userName: 'rfef', displayName: 'RFEF', accountType: 'institution' as const, description: 'Royal Spanish Football Federation' },
        { id: 387, countryCode: 'es', userName: 'LaLiga', displayName: 'LaLiga', accountType: 'institution' as const, description: 'Spanish football league' },

        // ===================== ITALY (IT) =====================
        { id: 36, countryCode: 'it', userName: 'GiorgiaMeloni', displayName: 'Giorgia Meloni', accountType: 'government' as const, description: 'Prime Minister of Italy' },
        { id: 37, countryCode: 'it', userName: 'PalazzoChigi', displayName: 'Palazzo Chigi', accountType: 'government' as const, description: 'Italian Government' },
        { id: 38, countryCode: 'it', userName: 'ItalyMFA', displayName: 'Italy MFA', accountType: 'government' as const, description: 'Ministry of Foreign Affairs' },
        { id: 400, countryCode: 'it', userName: 'Antonio_Tajani', displayName: 'Antonio Tajani', accountType: 'government' as const, description: 'Deputy PM, Foreign Minister' },
        { id: 401, countryCode: 'it', userName: 'matteosalvinimi', displayName: 'Matteo Salvini', accountType: 'government' as const, description: 'Deputy PM, Infrastructure' },
        { id: 402, countryCode: 'it', userName: 'Quirinale', displayName: 'Quirinale', accountType: 'government' as const, description: 'Presidency of the Republic' },
        { id: 403, countryCode: 'it', userName: 'Montecitorio', displayName: 'Camera dei Deputati', accountType: 'government' as const, description: 'Chamber of Deputies' },
        { id: 404, countryCode: 'it', userName: 'SenatoStampa', displayName: 'Senato della Repubblica', accountType: 'government' as const, description: 'Italian Senate' },
        { id: 39, countryCode: 'it', userName: 'Agenzia_Ansa', displayName: 'ANSA', accountType: 'news_agency' as const, description: 'ANSA news agency' },
        { id: 40, countryCode: 'it', userName: 'repubblica', displayName: 'la Repubblica', accountType: 'news_agency' as const, description: 'la Repubblica newspaper' },
        { id: 405, countryCode: 'it', userName: 'Corriere', displayName: 'Corriere della Sera', accountType: 'news_agency' as const, description: 'Corriere della Sera' },
        { id: 406, countryCode: 'it', userName: 'LaStampa', displayName: 'La Stampa', accountType: 'news_agency' as const, description: 'La Stampa newspaper' },
        { id: 407, countryCode: 'it', userName: 'RaiNews', displayName: 'Rai News', accountType: 'news_agency' as const, description: 'RAI public broadcaster' },
        { id: 408, countryCode: 'it', userName: 'SkyTG24', displayName: 'Sky TG24', accountType: 'news_agency' as const, description: 'Sky TG24 news' },
        { id: 409, countryCode: 'it', userName: 'sole24ore', displayName: 'Il Sole 24 Ore', accountType: 'news_agency' as const, description: 'Financial newspaper' },
        { id: 410, countryCode: 'it', userName: 'fattoquotidiano', displayName: 'Il Fatto Quotidiano', accountType: 'news_agency' as const, description: 'Il Fatto Quotidiano' },
        { id: 411, countryCode: 'it', userName: 'Adnkronos', displayName: 'Adnkronos', accountType: 'news_agency' as const, description: 'Adnkronos news agency' },
        { id: 412, countryCode: 'it', userName: 'marcotravaglio', displayName: 'Marco Travaglio', accountType: 'journalist' as const, description: 'Director of Il Fatto Quotidiano' },
        { id: 413, countryCode: 'it', userName: 'EnricoMentana', displayName: 'Enrico Mentana', accountType: 'journalist' as const, description: 'Director of TG LA7' },
        { id: 414, countryCode: 'it', userName: 'fabfazio', displayName: 'Fabio Fazio', accountType: 'journalist' as const, description: 'TV host (Che Tempo Che Fa)' },
        { id: 415, countryCode: 'it', userName: 'BeppeSevergnini', displayName: 'Beppe Severgnini', accountType: 'journalist' as const, description: 'Corriere columnist' },
        { id: 416, countryCode: 'it', userName: 'FratellidItalia', displayName: 'Fratelli d Italia', accountType: 'political_party' as const, description: 'FdI party' },
        { id: 417, countryCode: 'it', userName: 'pdnetwork', displayName: 'Partito Democratico', accountType: 'political_party' as const, description: 'PD official' },
        { id: 418, countryCode: 'it', userName: 'EllySchlein', displayName: 'Elly Schlein', accountType: 'political_party' as const, description: 'PD Secretary' },
        { id: 419, countryCode: 'it', userName: 'GiuseppeConteIT', displayName: 'Giuseppe Conte', accountType: 'political_party' as const, description: 'M5S leader, former PM' },
        { id: 420, countryCode: 'it', userName: 'Mov5Stelle', displayName: 'Movimento 5 Stelle', accountType: 'political_party' as const, description: 'M5S official' },
        { id: 421, countryCode: 'it', userName: 'LegaSalvini', displayName: 'Lega', accountType: 'political_party' as const, description: 'Lega party' },
        { id: 422, countryCode: 'it', userName: 'forza_italia', displayName: 'Forza Italia', accountType: 'political_party' as const, description: 'Forza Italia party' },
        { id: 423, countryCode: 'it', userName: 'matteorenzi', displayName: 'Matteo Renzi', accountType: 'political_party' as const, description: 'Italia Viva leader' },
        { id: 424, countryCode: 'it', userName: 'CarloCalenda', displayName: 'Carlo Calenda', accountType: 'political_party' as const, description: 'Azione party leader' },
        { id: 425, countryCode: 'it', userName: 'bancaditalia', displayName: 'Banca d Italia', accountType: 'institution' as const, description: 'Bank of Italy' },
        { id: 426, countryCode: 'it', userName: 'SerieA', displayName: 'Serie A', accountType: 'institution' as const, description: 'Italian football league' },
        { id: 427, countryCode: 'it', userName: 'FIGC', displayName: 'FIGC', accountType: 'institution' as const, description: 'Italian Football Federation' },

        // ===================== RUSSIA (RU) =====================
        { id: 41, countryCode: 'ru', userName: 'KremlinRussia_E', displayName: 'President of Russia', accountType: 'government' as const, description: 'Kremlin English-language' },
        { id: 42, countryCode: 'ru', userName: 'mfa_russia', displayName: 'MFA Russia', accountType: 'government' as const, description: 'Ministry of Foreign Affairs (EN)' },
        { id: 440, countryCode: 'ru', userName: 'MedvedevRussiaE', displayName: 'Dmitry Medvedev', accountType: 'government' as const, description: 'Deputy Chair, Security Council' },
        { id: 441, countryCode: 'ru', userName: 'GovernmentRF', displayName: 'Government of Russia', accountType: 'government' as const, description: 'Russian Government (EN)' },
        { id: 442, countryCode: 'ru', userName: 'RusEmbUSA', displayName: 'Russian Embassy USA', accountType: 'government' as const, description: 'Embassy in the United States' },
        { id: 443, countryCode: 'ru', userName: 'mod_russia', displayName: 'Ministry of Defence', accountType: 'government' as const, description: 'Russian MoD English' },
        { id: 43, countryCode: 'ru', userName: 'tass_agency', displayName: 'TASS', accountType: 'news_agency' as const, description: 'TASS Russian News Agency' },
        { id: 444, countryCode: 'ru', userName: 'RT_com', displayName: 'RT', accountType: 'news_agency' as const, description: 'RT (Russia Today) English' },
        { id: 445, countryCode: 'ru', userName: 'ria_novosti', displayName: 'RIA Novosti', accountType: 'news_agency' as const, description: 'RIA Novosti news agency' },
        { id: 446, countryCode: 'ru', userName: 'interfax_news', displayName: 'Interfax', accountType: 'news_agency' as const, description: 'Interfax news agency' },
        { id: 447, countryCode: 'ru', userName: 'kommersant', displayName: 'Kommersant', accountType: 'news_agency' as const, description: 'Kommersant newspaper' },
        { id: 448, countryCode: 'ru', userName: 'novaya_gazeta', displayName: 'Novaya Gazeta', accountType: 'news_agency' as const, description: 'Independent newspaper' },
        { id: 449, countryCode: 'ru', userName: 'MeduzaProject', displayName: 'Meduza', accountType: 'news_agency' as const, description: 'Independent media (Latvia-based)' },
        { id: 450, countryCode: 'ru', userName: 'MoscowTimes', displayName: 'The Moscow Times', accountType: 'news_agency' as const, description: 'English-language newspaper' },
        { id: 451, countryCode: 'ru', userName: 'KevinRothrock', displayName: 'Kevin Rothrock', accountType: 'journalist' as const, description: 'Meduza English editor' },
        { id: 452, countryCode: 'ru', userName: 'maxseddon', displayName: 'Max Seddon', accountType: 'journalist' as const, description: 'FT Moscow bureau chief' },
        { id: 453, countryCode: 'ru', userName: 'juliaioffe', displayName: 'Julia Ioffe', accountType: 'journalist' as const, description: 'Russian-American journalist' },
        { id: 454, countryCode: 'ru', userName: 'Bank_of_Russia', displayName: 'Bank of Russia', accountType: 'institution' as const, description: 'Central Bank of Russia' },
        { id: 455, countryCode: 'ru', userName: 'roscosmos', displayName: 'Roscosmos', accountType: 'institution' as const, description: 'Russian space agency' },
    ]).onConflictDoNothing();

    console.log('✅ Twitter accounts seeded (or already exist)');
}

seedTwitter()
    .then(() => {
        console.log('🎉 Done!');
        process.exit(0);
    })
    .catch((error) => {
        console.error('❌ Failed:', error);
        process.exit(1);
    });
