import 'dotenv/config';
import { db } from '../config/db.js';
import { categories, rss_sources, twitter_accounts } from '../db/schema/index.js';

async function seed() {
    console.log('🌱 Seeding database...');

    // Insert categories (skip if already exists)
    await db.insert(categories).values([
        { id: 1, name: 'Politika', slug: 'politika', icon: '🏛️', color: '#3B82F6' },
        { id: 2, name: 'Ekonomi', slug: 'ekonomi', icon: '💰', color: '#10B981' },
        { id: 3, name: 'Spor', slug: 'spor', icon: '⚽', color: '#F59E0B' },
        { id: 4, name: 'Teknoloji', slug: 'teknoloji', icon: '💻', color: '#8B5CF6' },
        { id: 5, name: 'Sağlık', slug: 'saglik', icon: '🏥', color: '#EF4444' },
        { id: 6, name: 'Bilim', slug: 'bilim', icon: '🔬', color: '#06B6D4' },
        { id: 7, name: 'Kültür', slug: 'kultur', icon: '🎭', color: '#EC4899' },
        { id: 8, name: 'Dünya', slug: 'dunya', icon: '🌍', color: '#14B8A6' },
        { id: 9, name: 'Güvenlik', slug: 'guvenlik', icon: '🛡️', color: '#DC2626' },
        { id: 10, name: 'Enerji', slug: 'enerji', icon: '⚡', color: '#EA580C' },
        { id: 11, name: 'Jeopolitik', slug: 'jeopolitik', icon: '🗺️', color: '#7C3AED' },
    ]).onConflictDoNothing();
    console.log('✅ Categories seeded (or already exist)');

    // Insert RSS sources with government alignment data
    await db.insert(rss_sources).values([
        // Turkey
        {
            id: 1,
            countryCode: 'tr',
            sourceName: 'Hürriyet',
            sourceLogoUrl: 'https://logo.clearbit.com/hurriyet.com.tr',
            rssUrl: 'https://www.hurriyet.com.tr/rss/anasayfa',
            isActive: true,
            biasScoreSystem: 5.5,
            govAlignmentScore: -1,
            govAlignmentLabel: 'Muhalefete Eğilimli',
            govAlignmentConfidence: 0.72,
            govAlignmentNotes: 'DYH grubu, editoryal çizgide iktidar politikalarına eleştirel vurgular daha sık.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 2,
            countryCode: 'tr',
            sourceName: 'Sözcü',
            sourceLogoUrl: 'https://logo.clearbit.com/sozcu.com.tr',
            rssUrl: 'https://www.sozcu.com.tr/feed/',
            isActive: true,
            biasScoreSystem: 4.0,
            govAlignmentScore: -4,
            govAlignmentLabel: 'Muhalefete Yakın',
            govAlignmentConfidence: 0.85,
            govAlignmentNotes: 'Güçlü muhalefet yanlısı editoryal çizgi.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 3,
            countryCode: 'tr',
            sourceName: 'NTV',
            sourceLogoUrl: 'https://logo.clearbit.com/ntv.com.tr',
            rssUrl: 'https://www.ntv.com.tr/gundem.rss',
            isActive: true,
            biasScoreSystem: 6.5,
            govAlignmentScore: 0,
            govAlignmentLabel: 'Karışık / Merkez',
            govAlignmentConfidence: 0.68,
            govAlignmentNotes: 'Görece dengeli yayın politikası.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 4,
            countryCode: 'tr',
            sourceName: 'Sabah',
            sourceLogoUrl: 'https://logo.clearbit.com/sabah.com.tr',
            rssUrl: 'https://www.sabah.com.tr/rss/anasayfa.xml',
            isActive: true,
            biasScoreSystem: 3.0,
            govAlignmentScore: 4,
            govAlignmentLabel: 'İktidara Yakın',
            govAlignmentConfidence: 0.88,
            govAlignmentNotes: 'Turkuaz medya grubu, iktidar yanlısı editoryal çizgi.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 5,
            countryCode: 'tr',
            sourceName: 'Cumhuriyet',
            sourceLogoUrl: 'https://logo.clearbit.com/cumhuriyet.com.tr',
            rssUrl: 'https://www.cumhuriyet.com.tr/rss',
            isActive: true,
            biasScoreSystem: 4.0,
            govAlignmentScore: -4,
            govAlignmentLabel: 'Muhalefete Yakın',
            govAlignmentConfidence: 0.90,
            govAlignmentNotes: 'Sol/laik çizgi, güçlü muhalefet yanlısı.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 6,
            countryCode: 'tr',
            sourceName: 'TRT Haber',
            sourceLogoUrl: 'https://logo.clearbit.com/trthaber.com',
            rssUrl: 'https://www.trthaber.com/sondakika.rss',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 4,
            govAlignmentLabel: 'İktidara Yakın',
            govAlignmentConfidence: 0.95,
            govAlignmentNotes: 'Resmi yayın kuruluşu.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 7,
            countryCode: 'tr',
            sourceName: 'CNN Türk',
            sourceLogoUrl: 'https://logo.clearbit.com/cnnturk.com',
            rssUrl: 'https://www.cnnturk.com/feed/rss/all/news',
            isActive: true,
            biasScoreSystem: 5.5,
            govAlignmentScore: 1,
            govAlignmentLabel: 'İktidara Eğilimli',
            govAlignmentConfidence: 0.70,
            govAlignmentNotes: 'Demirören medya grubu, merkez-sağ çizgi.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 8,
            countryCode: 'tr',
            sourceName: 'Milliyet',
            sourceLogoUrl: 'https://logo.clearbit.com/milliyet.com.tr',
            rssUrl: 'https://www.milliyet.com.tr/rss/rssNew/gundemRss.xml',
            isActive: true,
            biasScoreSystem: 5.5,
            govAlignmentScore: 1,
            govAlignmentLabel: 'İktidara Eğilimli',
            govAlignmentConfidence: 0.72,
            govAlignmentNotes: 'Demirören medya grubu.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 33,
            countryCode: 'tr',
            sourceName: 'Haberturk RSS',
            sourceLogoUrl: 'https://logo.clearbit.com/haberturk.com',
            rssUrl: 'https://haberturk.com/rss',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 1,
            govAlignmentLabel: 'İktidara Eğilimli',
            govAlignmentConfidence: 0.65,
            govAlignmentNotes: 'Ciner medya grubu, merkez-sağ çizgi.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 34,
            countryCode: 'tr',
            sourceName: 'Haberturk Ekonomi',
            sourceLogoUrl: 'https://logo.clearbit.com/haberturk.com',
            rssUrl: 'https://haberturk.com/rss/ekonomi.xml',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 1,
            govAlignmentLabel: 'İktidara Eğilimli',
            govAlignmentConfidence: 0.65,
            govAlignmentNotes: 'Ciner medya grubu, ekonomi haberleri.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 35,
            countryCode: 'tr',
            sourceName: 'Haberturk Gundem',
            sourceLogoUrl: 'https://logo.clearbit.com/haberturk.com',
            rssUrl: 'https://haberturk.com/rss/kategori/gundem.xml',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 1,
            govAlignmentLabel: 'İktidara Eğilimli',
            govAlignmentConfidence: 0.65,
            govAlignmentNotes: 'Ciner medya grubu, gündem haberleri.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 36,
            countryCode: 'tr',
            sourceName: 'Haberler.com',
            sourceLogoUrl: 'https://logo.clearbit.com/haberler.com',
            rssUrl: 'https://rss.haberler.com/rss.asp',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentLabel: 'Karışık / Merkez',
            govAlignmentConfidence: 0.55,
            govAlignmentNotes: 'Haber agregator, farklı kaynaklardan içerik toplar.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 37,
            countryCode: 'tr',
            sourceName: 'Haber7',
            sourceLogoUrl: 'https://logo.clearbit.com/haber7.com',
            rssUrl: 'https://i12.haber7.net/sondakika/news.xml',
            isActive: true,
            biasScoreSystem: 4.0,
            govAlignmentScore: 3,
            govAlignmentLabel: 'İktidara Yakın',
            govAlignmentConfidence: 0.75,
            govAlignmentNotes: 'Muhafazakâr çizgi, iktidar yanlısı editoryal politika.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 38,
            countryCode: 'tr',
            sourceName: 'Vatan',
            sourceLogoUrl: 'https://logo.clearbit.com/gazetevatan.com',
            rssUrl: 'https://gazetevatan.com/rss/gundem.xml',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 1,
            govAlignmentLabel: 'İktidara Eğilimli',
            govAlignmentConfidence: 0.60,
            govAlignmentNotes: 'Demirören medya grubu.',
            govAlignmentLastUpdated: new Date(),
        },
        {
            id: 39,
            countryCode: 'tr',
            sourceName: 'SoL Haber',
            sourceLogoUrl: 'https://logo.clearbit.com/sol.org.tr',
            rssUrl: 'https://haber.sol.org.tr/rss.xml',
            isActive: true,
            biasScoreSystem: 3.0,
            govAlignmentScore: -5,
            govAlignmentLabel: 'Muhalefete Yakın',
            govAlignmentConfidence: 0.92,
            govAlignmentNotes: 'Sol/sosyalist çizgi, güçlü muhalefet yanlısı.',
            govAlignmentLastUpdated: new Date(),
        },

        // Germany
        {
            id: 9,
            countryCode: 'de',
            sourceName: 'Der Spiegel',
            sourceLogoUrl: 'https://via.placeholder.com/100x100?text=Spiegel',
            rssUrl: 'https://www.spiegel.de/schlagzeilen/index.rss',
            isActive: true,
            biasScoreSystem: 7.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 10,
            countryCode: 'de',
            sourceName: 'Bild',
            sourceLogoUrl: 'https://via.placeholder.com/100x100?text=Bild',
            rssUrl: 'https://www.bild.de/rssfeeds/vw-alles/vw-alles-26970192,sort=1,view=rss2.bild.xml',
            isActive: true,
            biasScoreSystem: 4.5,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 24,
            countryCode: 'de',
            sourceName: 'Zeit Politics',
            sourceLogoUrl: 'https://logo.clearbit.com/zeit.de',
            rssUrl: 'https://newsfeed.zeit.de/politik/index',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 25,
            countryCode: 'de',
            sourceName: 'The Local DE',
            sourceLogoUrl: 'https://logo.clearbit.com/thelocal.de',
            rssUrl: 'https://feeds.thelocal.com/rss/de',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 26,
            countryCode: 'de',
            sourceName: 'Tagesschau',
            sourceLogoUrl: 'https://logo.clearbit.com/tagesschau.de',
            rssUrl: 'https://www.tagesschau.de/xml/rss2/',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 27,
            countryCode: 'de',
            sourceName: 'FAZ',
            sourceLogoUrl: 'https://logo.clearbit.com/faz.net',
            rssUrl: 'https://faz.net/rss/aktuell',
            isActive: true,
            biasScoreSystem: 6.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 28,
            countryCode: 'de',
            sourceName: 'DW Top',
            sourceLogoUrl: 'https://logo.clearbit.com/dw.com',
            rssUrl: 'https://rss.dw.com/rdf/rss-en-top',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 29,
            countryCode: 'de',
            sourceName: 'DW All',
            sourceLogoUrl: 'https://logo.clearbit.com/dw.com',
            rssUrl: 'https://rss.dw.com/rdf/rss-en-all',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },

        // USA
        {
            id: 11,
            countryCode: 'us',
            sourceName: 'CNN',
            sourceLogoUrl: 'https://via.placeholder.com/100x100?text=CNN',
            rssUrl: 'http://rss.cnn.com/rss/edition.rss',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 12,
            countryCode: 'us',
            sourceName: 'Reuters',
            sourceLogoUrl: 'https://via.placeholder.com/100x100?text=Reuters',
            rssUrl: 'https://www.reutersagency.com/feed/',
            isActive: true,
            biasScoreSystem: 8.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 13,
            countryCode: 'us',
            sourceName: 'The Guardian',
            sourceLogoUrl: 'https://via.placeholder.com/100x100?text=Guardian',
            rssUrl: 'https://www.theguardian.com/world/rss',
            isActive: true,
            biasScoreSystem: 6.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 30,
            countryCode: 'us',
            sourceName: 'PBS Politics',
            sourceLogoUrl: 'https://logo.clearbit.com/pbs.org',
            rssUrl: 'https://www.pbs.org/newshour/politics/feed',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 31,
            countryCode: 'us',
            sourceName: 'Reuters Politics',
            sourceLogoUrl: 'https://logo.clearbit.com/reuters.com',
            rssUrl: 'https://feeds.reuters.com/Reuters/PoliticsNews',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },

        // UK
        {
            id: 14,
            countryCode: 'uk',
            sourceName: 'Politics.co.uk',
            sourceLogoUrl: 'https://logo.clearbit.com/politics.co.uk',
            rssUrl: 'https://politics.co.uk/feed',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 15,
            countryCode: 'uk',
            sourceName: 'BBC Business',
            sourceLogoUrl: 'https://logo.clearbit.com/bbc.co.uk',
            rssUrl: 'https://feeds.bbci.co.uk/news/business/rss.xml',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 16,
            countryCode: 'uk',
            sourceName: 'BBC News',
            sourceLogoUrl: 'https://logo.clearbit.com/bbc.co.uk',
            rssUrl: 'https://feeds.bbci.co.uk/news/rss.xml',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },

        // France
        {
            id: 17,
            countryCode: 'fr',
            sourceName: 'France TV Politics',
            sourceLogoUrl: 'https://logo.clearbit.com/francetvinfo.fr',
            rssUrl: 'https://francetvinfo.fr/politique.rss',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 18,
            countryCode: 'fr',
            sourceName: 'France TV Economy',
            sourceLogoUrl: 'https://logo.clearbit.com/francetvinfo.fr',
            rssUrl: 'https://francetvinfo.fr/economie.rss',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },

        // Italy
        {
            id: 19,
            countryCode: 'it',
            sourceName: 'Corriere Politica',
            sourceLogoUrl: 'https://logo.clearbit.com/corriere.it',
            rssUrl: 'https://corriere.it/dynamic-feed/rss/politica',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 20,
            countryCode: 'it',
            sourceName: 'Corriere Economia',
            sourceLogoUrl: 'https://logo.clearbit.com/corriere.it',
            rssUrl: 'https://corriere.it/dynamic-feed/rss/economia',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },

        // Spain
        {
            id: 21,
            countryCode: 'es',
            sourceName: 'El Mundo',
            sourceLogoUrl: 'https://logo.clearbit.com/elmundo.es',
            rssUrl: 'https://e00-elmundo.uecdn.es/rss/portada.xml',
            isActive: true,
            biasScoreSystem: 6.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 22,
            countryCode: 'es',
            sourceName: 'El Diario',
            sourceLogoUrl: 'https://logo.clearbit.com/eldiario.es',
            rssUrl: 'https://eldiario.es/rss',
            isActive: true,
            biasScoreSystem: 4.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 23,
            countryCode: 'es',
            sourceName: 'El Espanol',
            sourceLogoUrl: 'https://logo.clearbit.com/elespanol.com',
            rssUrl: 'https://elespanal.com/rss/espana',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },

        // Russia
        {
            id: 32,
            countryCode: 'ru',
            sourceName: 'Sputnik Globe',
            sourceLogoUrl: 'https://logo.clearbit.com/sputnikglobe.com',
            rssUrl: 'https://sputnikglobe.com/export/rss2/russia',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        // --- WorldMonitor-inspired geopolitical/defense/energy sources ---

        // Global / US - Geopolitics & Defense
        {
            id: 40,
            countryCode: 'us',
            sourceName: 'Al Jazeera English',
            sourceLogoUrl: 'https://logo.clearbit.com/aljazeera.com',
            rssUrl: 'https://www.aljazeera.com/xml/rss/all.xml',
            isActive: true,
            biasScoreSystem: 5.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
            govAlignmentNotes: 'Qatar-based, independent editorial line on global affairs.',
        },
        {
            id: 41,
            countryCode: 'us',
            sourceName: 'AP News',
            sourceLogoUrl: 'https://logo.clearbit.com/apnews.com',
            rssUrl: 'https://rsshub.app/apnews/topics/world-news',
            isActive: true,
            biasScoreSystem: 8.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
            govAlignmentNotes: 'Wire service, highly factual.',
        },
        {
            id: 42,
            countryCode: 'us',
            sourceName: 'Defense One',
            sourceLogoUrl: 'https://logo.clearbit.com/defenseone.com',
            rssUrl: 'https://www.defenseone.com/rss/',
            isActive: true,
            biasScoreSystem: 6.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
            govAlignmentNotes: 'US defense and national security focus.',
        },
        {
            id: 43,
            countryCode: 'us',
            sourceName: 'The Diplomat',
            sourceLogoUrl: 'https://logo.clearbit.com/thediplomat.com',
            rssUrl: 'https://thediplomat.com/feed/',
            isActive: true,
            biasScoreSystem: 7.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
            govAlignmentNotes: 'Asia-Pacific geopolitics focus.',
        },
        {
            id: 44,
            countryCode: 'us',
            sourceName: 'NPR World',
            sourceLogoUrl: 'https://logo.clearbit.com/npr.org',
            rssUrl: 'https://feeds.npr.org/1004/rss.xml',
            isActive: true,
            biasScoreSystem: 6.5,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },

        // UK - additional
        {
            id: 45,
            countryCode: 'uk',
            sourceName: 'BBC World',
            sourceLogoUrl: 'https://logo.clearbit.com/bbc.co.uk',
            rssUrl: 'http://feeds.bbci.co.uk/news/world/rss.xml',
            isActive: true,
            biasScoreSystem: 7.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 46,
            countryCode: 'uk',
            sourceName: 'The Guardian World',
            sourceLogoUrl: 'https://logo.clearbit.com/theguardian.com',
            rssUrl: 'https://www.theguardian.com/world/rss',
            isActive: true,
            biasScoreSystem: 5.5,
            govAlignmentScore: -2,
            govAlignmentLabel: 'Centre-Left',
            govAlignmentConfidence: 0.7,
        },
        {
            id: 47,
            countryCode: 'uk',
            sourceName: 'Sky News',
            sourceLogoUrl: 'https://logo.clearbit.com/news.sky.com',
            rssUrl: 'https://feeds.skynews.com/feeds/rss/world.xml',
            isActive: true,
            biasScoreSystem: 5.5,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },

        // Germany - additional
        {
            id: 48,
            countryCode: 'de',
            sourceName: 'DW Politik',
            sourceLogoUrl: 'https://logo.clearbit.com/dw.com',
            rssUrl: 'https://rss.dw.com/xml/rss-de-pol',
            isActive: true,
            biasScoreSystem: 6.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },

        // France - additional
        {
            id: 49,
            countryCode: 'fr',
            sourceName: 'France 24',
            sourceLogoUrl: 'https://logo.clearbit.com/france24.com',
            rssUrl: 'https://www.france24.com/en/rss',
            isActive: true,
            biasScoreSystem: 6.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },
        {
            id: 50,
            countryCode: 'fr',
            sourceName: 'Le Monde',
            sourceLogoUrl: 'https://logo.clearbit.com/lemonde.fr',
            rssUrl: 'https://www.lemonde.fr/rss/une.xml',
            isActive: true,
            biasScoreSystem: 7.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },

        // Italy - additional
        {
            id: 51,
            countryCode: 'it',
            sourceName: 'ANSA',
            sourceLogoUrl: 'https://logo.clearbit.com/ansa.it',
            rssUrl: 'https://www.ansa.it/sito/ansait_rss.xml',
            isActive: true,
            biasScoreSystem: 7.0,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
            govAlignmentNotes: 'Italian wire service.',
        },
        {
            id: 52,
            countryCode: 'it',
            sourceName: 'La Repubblica',
            sourceLogoUrl: 'https://logo.clearbit.com/repubblica.it',
            rssUrl: 'https://www.repubblica.it/rss/homepage/rss2.0.xml',
            isActive: true,
            biasScoreSystem: 5.5,
            govAlignmentScore: -1,
            govAlignmentConfidence: 0.6,
        },

        // Spain - additional
        {
            id: 53,
            countryCode: 'es',
            sourceName: 'El Pais',
            sourceLogoUrl: 'https://logo.clearbit.com/elpais.com',
            rssUrl: 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada',
            isActive: true,
            biasScoreSystem: 6.5,
            govAlignmentScore: 0,
            govAlignmentConfidence: 0.5,
        },

        // Russia - additional
        {
            id: 54,
            countryCode: 'ru',
            sourceName: 'TASS English',
            sourceLogoUrl: 'https://logo.clearbit.com/tass.com',
            rssUrl: 'https://tass.com/rss/v2.xml',
            isActive: true,
            biasScoreSystem: 3.0,
            govAlignmentScore: 5,
            govAlignmentLabel: 'State-owned',
            govAlignmentConfidence: 0.95,
            govAlignmentNotes: 'Russian state news agency.',
        },
        {
            id: 55,
            countryCode: 'ru',
            sourceName: 'Moscow Times',
            sourceLogoUrl: 'https://logo.clearbit.com/themoscowtimes.com',
            rssUrl: 'https://www.themoscowtimes.com/rss/news',
            isActive: true,
            biasScoreSystem: 6.0,
            govAlignmentScore: -3,
            govAlignmentLabel: 'Independent/Critical',
            govAlignmentConfidence: 0.8,
            govAlignmentNotes: 'Independent English-language outlet, critical of Kremlin.',
        },
    ]).onConflictDoNothing();
    console.log('✅ RSS sources seeded (or already exist)');

    // Insert Twitter accounts for digest enrichment
    await db.insert(twitter_accounts).values([
        // Turkey — Government & official institutions
        { id: 1, countryCode: 'tr', userName: 'RTErdogan', displayName: 'Recep Tayyip Erdogan', accountType: 'government' as const, description: 'Cumhurbaskani' },
        { id: 2, countryCode: 'tr', userName: 'tcbaskanlik', displayName: 'T.C. Cumhurbaskanligi', accountType: 'government' as const, description: 'Cumhurbaskanligi resmi hesabi' },
        { id: 3, countryCode: 'tr', userName: 'TC_Disisleri', displayName: 'TC Disisleri Bakanligi', accountType: 'government' as const, description: 'Disisleri Bakanligi' },
        { id: 4, countryCode: 'tr', userName: 'iaborakisim', displayName: 'Iletisim Baskanligi', accountType: 'government' as const, description: 'Cumhurbaskanligi Iletisim Baskanligi' },
        { id: 5, countryCode: 'tr', userName: 'aaborakans', displayName: 'Anadolu Ajansi', accountType: 'news_agency' as const, description: 'Resmi haber ajansi (Turkce)' },
        { id: 6, countryCode: 'tr', userName: 'AnadoluAgency', displayName: 'Anadolu Agency', accountType: 'news_agency' as const, description: 'Anadolu Agency (English)' },
        { id: 7, countryCode: 'tr', userName: 'trthaber', displayName: 'TRT Haber', accountType: 'news_agency' as const, description: 'TRT devlet yayin kurumu' },
        { id: 44, countryCode: 'tr', userName: 'HakanFidan', displayName: 'Hakan Fidan', accountType: 'government' as const, description: 'Disisleri Bakani' },
        { id: 45, countryCode: 'tr', userName: 'fahrettinaltun', displayName: 'Fahrettin Altun', accountType: 'government' as const, description: 'Iletisim Baskani' },
        { id: 46, countryCode: 'tr', userName: 'omerrcelik', displayName: 'Omer Celik', accountType: 'government' as const, description: 'AK Parti Sozcusu' },
        { id: 47, countryCode: 'tr', userName: 'suleymansoylu', displayName: 'Suleyman Soylu', accountType: 'government' as const, description: 'Eski Icisleri Bakani' },
        { id: 48, countryCode: 'tr', userName: 'drfahrettinkoca', displayName: 'Fahrettin Koca', accountType: 'government' as const, description: 'Eski Saglik Bakani' },
        { id: 49, countryCode: 'tr', userName: 'varank', displayName: 'Mustafa Varank', accountType: 'government' as const, description: 'Eski Sanayi Bakani' },
        { id: 50, countryCode: 'tr', userName: 'memetsimsek', displayName: 'Mehmet Simsek', accountType: 'government' as const, description: 'Hazine ve Maliye Bakani' },
        { id: 51, countryCode: 'tr', userName: 'AliYerlikaya', displayName: 'Ali Yerlikaya', accountType: 'government' as const, description: 'Icisleri Bakani' },
        { id: 52, countryCode: 'tr', userName: 'Yusuf__Tekin', displayName: 'Yusuf Tekin', accountType: 'government' as const, description: 'Milli Egitim Bakani' },
        { id: 53, countryCode: 'tr', userName: 'cevdetyilmaz', displayName: 'Cevdet Yilmaz', accountType: 'government' as const, description: 'Cumhurbaskani Yardimcisi' },
        { id: 54, countryCode: 'tr', userName: 'NumanKurtulmus', displayName: 'Numan Kurtulmus', accountType: 'government' as const, description: 'TBMM Baskani' },
        { id: 55, countryCode: 'tr', userName: 'mehmetmus', displayName: 'Mehmet Mus', accountType: 'government' as const, description: 'Ticaret Bakani' },
        { id: 56, countryCode: 'tr', userName: 'AlparslanBayrak', displayName: 'Alparslan Bayraktar', accountType: 'government' as const, description: 'Enerji Bakani' },
        { id: 57, countryCode: 'tr', userName: 'a_uraloglu', displayName: 'Abdulkadir Uraloglu', accountType: 'government' as const, description: 'Ulastirma Bakani' },
        { id: 58, countryCode: 'tr', userName: 'AbdulkadirUral', displayName: 'Abdulkadir Ural', accountType: 'government' as const, description: 'Hukumet yetkilisi' },
        { id: 59, countryCode: 'tr', userName: 'Selcuk', displayName: 'Ziya Selcuk', accountType: 'government' as const, description: 'Eski MEB Bakani' },
        { id: 60, countryCode: 'tr', userName: 'efkan_ala', displayName: 'Efkan Ala', accountType: 'government' as const, description: 'Eski Icisleri Bakani' },
        { id: 61, countryCode: 'tr', userName: 'TC_Icisleri', displayName: 'Icisleri Bakanligi', accountType: 'government' as const, description: 'T.C. Icisleri Bakanligi' },
        { id: 62, countryCode: 'tr', userName: 'adalet_bakanligi', displayName: 'Adalet Bakanligi', accountType: 'government' as const, description: 'T.C. Adalet Bakanligi' },
        { id: 63, countryCode: 'tr', userName: 'AFADBaskanlik', displayName: 'AFAD', accountType: 'government' as const, description: 'Afet ve Acil Durum Yonetimi' },
        // Turkey — Political party leaders & politicians
        { id: 64, countryCode: 'tr', userName: 'dbdevletbahceli', displayName: 'Devlet Bahceli', accountType: 'political_party' as const, description: 'MHP Genel Baskani' },
        { id: 65, countryCode: 'tr', userName: 'eczozgurozel', displayName: 'Ozgur Ozel', accountType: 'political_party' as const, description: 'CHP Genel Baskani' },
        { id: 66, countryCode: 'tr', userName: 'erkbas', displayName: 'Erkbas', accountType: 'political_party' as const, description: 'Siyasetci' },
        { id: 67, countryCode: 'tr', userName: 'kilicdarogluk', displayName: 'Kemal Kilicdaroglu', accountType: 'political_party' as const, description: 'Eski CHP Genel Baskani' },
        { id: 68, countryCode: 'tr', userName: 'ekrem_imamoglu', displayName: 'Ekrem Imamoglu', accountType: 'political_party' as const, description: 'IBB Baskani' },
        { id: 69, countryCode: 'tr', userName: 'mansuryavas06', displayName: 'Mansur Yavas', accountType: 'political_party' as const, description: 'ABB Baskani' },
        { id: 70, countryCode: 'tr', userName: 'meral_aksener', displayName: 'Meral Aksener', accountType: 'political_party' as const, description: 'IYI Parti' },
        { id: 71, countryCode: 'tr', userName: 'alibabacan', displayName: 'Ali Babacan', accountType: 'political_party' as const, description: 'DEVA Partisi Genel Baskani' },
        { id: 72, countryCode: 'tr', userName: 'MDervisogluTR', displayName: 'Musavat Dervisoglu', accountType: 'political_party' as const, description: 'IYI Parti Genel Baskani' },
        { id: 73, countryCode: 'tr', userName: 'erbakanfatih', displayName: 'Fatih Erbakan', accountType: 'political_party' as const, description: 'Yeniden Refah Partisi' },
        { id: 74, countryCode: 'tr', userName: 'umitozdag', displayName: 'Umit Ozdag', accountType: 'political_party' as const, description: 'Zafer Partisi' },
        { id: 75, countryCode: 'tr', userName: 'MuharremInce', displayName: 'Muharrem Ince', accountType: 'political_party' as const, description: 'Memleket Partisi' },
        { id: 76, countryCode: 'tr', userName: 'Ahmet_Davutoglu', displayName: 'Ahmet Davutoglu', accountType: 'political_party' as const, description: 'Gelecek Partisi' },
        { id: 77, countryCode: 'tr', userName: 'Temel_Karamollaoglu', displayName: 'Temel Karamollaoglu', accountType: 'political_party' as const, description: 'Saadet Partisi' },
        { id: 78, countryCode: 'tr', userName: 'E_SemihYalcin', displayName: 'Semih Yalcin', accountType: 'political_party' as const, description: 'MHP Genel Baskan Yardimcisi' },
        { id: 79, countryCode: 'tr', userName: 'buyukataman', displayName: 'Buyukataman', accountType: 'political_party' as const, description: 'MHP' },
        { id: 80, countryCode: 'tr', userName: 'celal_adan', displayName: 'Celal Adan', accountType: 'political_party' as const, description: 'MHP' },
        { id: 81, countryCode: 'tr', userName: 'YildizFeti', displayName: 'Feti Yildiz', accountType: 'political_party' as const, description: 'Siyasetci' },
        { id: 82, countryCode: 'tr', userName: 'cenginyurt52', displayName: 'Cengin Yurt', accountType: 'political_party' as const, description: 'Siyasetci' },
        { id: 83, countryCode: 'tr', userName: 'serakadigil', displayName: 'Sera Kadigil', accountType: 'political_party' as const, description: 'TIP Milletvekili' },
        { id: 84, countryCode: 'tr', userName: 'ComezTurhan', displayName: 'Turhan Comez', accountType: 'political_party' as const, description: 'Siyasetci' },
        { id: 85, countryCode: 'tr', userName: 'MTanal', displayName: 'Mahmut Tanal', accountType: 'political_party' as const, description: 'CHP Milletvekili' },
        { id: 86, countryCode: 'tr', userName: 'tanjuozcanchp', displayName: 'Tanju Ozcan', accountType: 'political_party' as const, description: 'Bolu Belediye Baskani' },
        { id: 87, countryCode: 'tr', userName: 'HDPgenelmerkezi', displayName: 'HDP', accountType: 'political_party' as const, description: 'HDP Genel Merkezi' },
        { id: 88, countryCode: 'tr', userName: 'herkesicinCHP', displayName: 'CHP', accountType: 'political_party' as const, description: 'CHP Genel Merkezi' },
        // Turkey — Mayors
        { id: 89, countryCode: 'tr', userName: 'Ahmet_Aras', displayName: 'Ahmet Aras', accountType: 'political_party' as const, description: 'Bodrum Belediye Baskani' },
        { id: 90, countryCode: 'tr', userName: 'burcukoksal03', displayName: 'Burcu Koksal', accountType: 'political_party' as const, description: 'Afyon Belediye Baskani' },
        { id: 91, countryCode: 'tr', userName: 'OzlemCercioglu', displayName: 'Ozlem Cercioglu', accountType: 'political_party' as const, description: 'Aydin Belediye Baskani' },
        { id: 92, countryCode: 'tr', userName: 'vahap_secer', displayName: 'Vahap Secer', accountType: 'political_party' as const, description: 'Mersin Belediye Baskani' },
        { id: 93, countryCode: 'tr', userName: 'zeydankaralar01', displayName: 'Zeydan Karalar', accountType: 'political_party' as const, description: 'Adana Belediye Baskani' },
        { id: 94, countryCode: 'tr', userName: 'hamzahdag', displayName: 'Hamza Dag', accountType: 'political_party' as const, description: 'Izmir Belediye Baskani' },
        { id: 95, countryCode: 'tr', userName: 'mustafaelitas', displayName: 'Mustafa Elitas', accountType: 'political_party' as const, description: 'Kayseri Milletvekili' },
        { id: 96, countryCode: 'tr', userName: 'yusufziya_yilmaz', displayName: 'Yusuf Ziya Yilmaz', accountType: 'political_party' as const, description: 'Samsun Belediye Baskani' },
        { id: 97, countryCode: 'tr', userName: 'gamzetasciyer', displayName: 'Gamze Tasciyer', accountType: 'political_party' as const, description: 'Siyasetci' },
        // Turkey — Journalists & commentators
        { id: 98, countryCode: 'tr', userName: 'avdenizyucel', displayName: 'Deniz Yucel', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 99, countryCode: 'tr', userName: 'alimahir', displayName: 'Ali Mahir', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 100, countryCode: 'tr', userName: 'aysegul__dogan', displayName: 'Aysegul Dogan', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 101, countryCode: 'tr', userName: 'zorlu77', displayName: 'Zorlu', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 102, countryCode: 'tr', userName: 'birolaydinsp', displayName: 'Birol Aydin', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 103, countryCode: 'tr', userName: 'avidrissahin', displayName: 'Idris Sahin', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 104, countryCode: 'tr', userName: 'SerkanRamanli', displayName: 'Serkan Ramanli', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 105, countryCode: 'tr', userName: 'vedatbilgn', displayName: 'Vedat Bilgin', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 106, countryCode: 'tr', userName: 'nevsinmengu', displayName: 'Nevsin Mengu', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 107, countryCode: 'tr', userName: 'cuneytozdemir', displayName: 'Cuneyt Ozdemir', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 108, countryCode: 'tr', userName: 'haskologlu', displayName: 'Haskologlu', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 109, countryCode: 'tr', userName: 'sakinan1968', displayName: 'Sakinan', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 110, countryCode: 'tr', userName: 'eafyoncu', displayName: 'Erhan Afyoncu', accountType: 'journalist' as const, description: 'Tarihci / Gazeteci' },
        { id: 111, countryCode: 'tr', userName: 'm_cemilkilic', displayName: 'M. Cemil Kilic', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 112, countryCode: 'tr', userName: 'merdanyanardag', displayName: 'Merdan Yanardag', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 113, countryCode: 'tr', userName: 'candundaradasi', displayName: 'Can Dundar', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 114, countryCode: 'tr', userName: 'eceuner12', displayName: 'Ece Uner', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 115, countryCode: 'tr', userName: 'emrahgulsunar', displayName: 'Emrah Gulsunar', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 116, countryCode: 'tr', userName: 'ismailari_', displayName: 'Ismail Ari', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 117, countryCode: 'tr', userName: 'ismailsaymaz', displayName: 'Ismail Saymaz', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 118, countryCode: 'tr', userName: 'kucukkayaismail', displayName: 'Ismail Kucukkaya', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 119, countryCode: 'tr', userName: 'muratagirel', displayName: 'Murat Agirel', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 120, countryCode: 'tr', userName: 'baristerkoglu', displayName: 'Baris Terkoglu', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 121, countryCode: 'tr', userName: 'barispehlivan', displayName: 'Baris Pehlivan', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 122, countryCode: 'tr', userName: 'ugur_dundar', displayName: 'Ugur Dundar', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 123, countryCode: 'tr', userName: 'fatihportakal', displayName: 'Fatih Portakal', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 124, countryCode: 'tr', userName: 'yilmazozdil', displayName: 'Yilmaz Ozdil', accountType: 'journalist' as const, description: 'Gazeteci / Yazar' },
        { id: 125, countryCode: 'tr', userName: 'sedat_peker', displayName: 'Sedat Peker', accountType: 'journalist' as const, description: 'Kamuoyu etkili kisi' },
        { id: 126, countryCode: 'tr', userName: 'barisyarkadas', displayName: 'Baris Yarkadas', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 127, countryCode: 'tr', userName: 'saygi_ozturk', displayName: 'Saygi Ozturk', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 128, countryCode: 'tr', userName: 'muratyetkin2', displayName: 'Murat Yetkin', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 129, countryCode: 'tr', userName: 'fehimtastekin', displayName: 'Fehim Tastekin', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 130, countryCode: 'tr', userName: 'abdulkadir_selvi', displayName: 'Abdulkadir Selvi', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 131, countryCode: 'tr', userName: 'fatihaltayli', displayName: 'Fatih Altayli', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 132, countryCode: 'tr', userName: 'timursoykan', displayName: 'Timur Soykan', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 133, countryCode: 'tr', userName: 'cigdemtoker', displayName: 'Cigdem Toker', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 134, countryCode: 'tr', userName: 'alicanuludag', displayName: 'Ali Can Uludag', accountType: 'journalist' as const, description: 'Gazeteci' },
        { id: 135, countryCode: 'tr', userName: 'sahmetsahmet', displayName: 'Sahmet', accountType: 'journalist' as const, description: 'Gazeteci' },
        // Turkey — Economists & finance
        { id: 136, countryCode: 'tr', userName: 'mahfiegilmez', displayName: 'Mahfi Egilmez', accountType: 'journalist' as const, description: 'Ekonomist' },
        { id: 137, countryCode: 'tr', userName: 'OzgrDemirtas', displayName: 'Ozgur Demirtas', accountType: 'journalist' as const, description: 'Ekonomist' },
        { id: 138, countryCode: 'tr', userName: 'emrealkin1969', displayName: 'Emre Alkin', accountType: 'journalist' as const, description: 'Ekonomist' },
        { id: 139, countryCode: 'tr', userName: 'iriscibre', displayName: 'Ibrahim Risci', accountType: 'journalist' as const, description: 'Ekonomist' },
        { id: 140, countryCode: 'tr', userName: 'mustafasonmez', displayName: 'Mustafa Sonmez', accountType: 'journalist' as const, description: 'Ekonomist' },
        { id: 141, countryCode: 'tr', userName: 'ugurses', displayName: 'Ugur Gurses', accountType: 'journalist' as const, description: 'Ekonomi yazari' },
        { id: 142, countryCode: 'tr', userName: 'senolguldur', displayName: 'Senol Guldur', accountType: 'journalist' as const, description: 'Ekonomi yazari' },
        { id: 143, countryCode: 'tr', userName: 'AtillaYesilada7', displayName: 'Atilla Yesilada', accountType: 'journalist' as const, description: 'Ekonomist' },
        { id: 144, countryCode: 'tr', userName: 'sozcumurat', displayName: 'Murat Sozcu', accountType: 'journalist' as const, description: 'Ekonomi yazari' },
        { id: 145, countryCode: 'tr', userName: 'ekonomikanaliz', displayName: 'Ekonomik Analiz', accountType: 'journalist' as const, description: 'Ekonomi analizi' },
        { id: 146, countryCode: 'tr', userName: 'RefetGurkaynak', displayName: 'Refet Gurkaynak', accountType: 'journalist' as const, description: 'Ekonomist / Akademisyen' },
        { id: 147, countryCode: 'tr', userName: 'yagosabuncuoglu', displayName: 'Yagiz Sabuncuoglu', accountType: 'journalist' as const, description: 'Spor gazetecisi' },
        { id: 148, countryCode: 'tr', userName: 'ertemsener', displayName: 'Ertem Sener', accountType: 'journalist' as const, description: 'Spor gazetecisi' },
        { id: 149, countryCode: 'tr', userName: 'metinfeyzioglu', displayName: 'Metin Feyzioglu', accountType: 'journalist' as const, description: 'Hukukcu' },
        { id: 150, countryCode: 'tr', userName: 'gonencgurkaynak', displayName: 'Gonenc Gurkaynak', accountType: 'journalist' as const, description: 'Hukukcu' },
        // Turkey — Institutions & legal
        { id: 151, countryCode: 'tr', userName: 'istbassavcisi', displayName: 'Istanbul Bassavciligi', accountType: 'institution' as const, description: 'Istanbul Cumhuriyet Bassavciligi' },
        { id: 152, countryCode: 'tr', userName: 'RHisarciklioglu', displayName: 'Rifat Hisarciklioglu', accountType: 'institution' as const, description: 'TOBB Baskani' },
        // Turkey — Media & news organizations
        { id: 153, countryCode: 'tr', userName: 'pusholder', displayName: 'Pusholder', accountType: 'news_agency' as const, description: 'Kamuoyu arastirma' },
        { id: 154, countryCode: 'tr', userName: 'Darkwebhaber', displayName: 'Darkweb Haber', accountType: 'news_agency' as const, description: 'Haber platformu' },
        { id: 155, countryCode: 'tr', userName: 't24comtr', displayName: 'T24', accountType: 'news_agency' as const, description: 'Bagimsiz haber sitesi' },
        { id: 156, countryCode: 'tr', userName: 'gazeteduvar', displayName: 'Gazete Duvar', accountType: 'news_agency' as const, description: 'Haber sitesi' },
        { id: 157, countryCode: 'tr', userName: 'medyascope', displayName: 'Medyascope', accountType: 'news_agency' as const, description: 'Dijital medya' },
        { id: 158, countryCode: 'tr', userName: 'solcugazete', displayName: 'Sol Gazete', accountType: 'news_agency' as const, description: 'Haber sitesi' },
        { id: 159, countryCode: 'tr', userName: 'dokuz8haber', displayName: 'Dokuz8 Haber', accountType: 'news_agency' as const, description: 'Haber ajansi' },
        { id: 160, countryCode: 'tr', userName: 'bbcturkce', displayName: 'BBC Turkce', accountType: 'news_agency' as const, description: 'BBC Turkce servisi' },
        { id: 161, countryCode: 'tr', userName: 'dw_turkce', displayName: 'DW Turkce', accountType: 'news_agency' as const, description: 'Deutsche Welle Turkce' },
        { id: 162, countryCode: 'tr', userName: 'voaturkce', displayName: 'VOA Turkce', accountType: 'news_agency' as const, description: 'Amerika nin Sesi' },
        { id: 163, countryCode: 'tr', userName: 'anadoluajansi', displayName: 'Anadolu Ajansi (TR)', accountType: 'news_agency' as const, description: 'Anadolu Ajansi Turkce' },
        { id: 164, countryCode: 'tr', userName: 'etkilihaberyeni', displayName: 'Etkili Haber', accountType: 'news_agency' as const, description: 'Haber platformu' },
        { id: 165, countryCode: 'tr', userName: 'tkrgazete', displayName: 'TKR Gazete', accountType: 'news_agency' as const, description: 'Haber sitesi' },
        { id: 166, countryCode: 'tr', userName: 'bosunatiklama', displayName: 'Bosuna Tiklama', accountType: 'news_agency' as const, description: 'Dogrulama platformu' },
        { id: 167, countryCode: 'tr', userName: 'proftpmedya', displayName: 'Prof TP Medya', accountType: 'news_agency' as const, description: 'Medya analizi' },
        { id: 168, countryCode: 'tr', userName: 'haber', displayName: 'Haber', accountType: 'news_agency' as const, description: 'Haber hesabi' },
        // Turkey — Sports
        { id: 169, countryCode: 'tr', userName: 'Fenerbahce', displayName: 'Fenerbahce', accountType: 'institution' as const, description: 'Fenerbahce SK' },
        { id: 170, countryCode: 'tr', userName: 'GalatasaraySK', displayName: 'Galatasaray', accountType: 'institution' as const, description: 'Galatasaray SK' },
        { id: 171, countryCode: 'tr', userName: 'Besiktas', displayName: 'Besiktas', accountType: 'institution' as const, description: 'Besiktas JK' },
        { id: 172, countryCode: 'tr', userName: 'Trabzonspor', displayName: 'Trabzonspor', accountType: 'institution' as const, description: 'Trabzonspor' },
        { id: 173, countryCode: 'tr', userName: 'TFF_Org', displayName: 'TFF', accountType: 'institution' as const, description: 'Turkiye Futbol Federasyonu' },
        { id: 174, countryCode: 'tr', userName: 'demarkesports', displayName: 'Demarke Sports', accountType: 'institution' as const, description: 'Spor haberleri' },
        { id: 175, countryCode: 'tr', userName: 'sportsdigitale', displayName: 'Sports Digitale', accountType: 'institution' as const, description: 'Dijital spor haberleri' },
        { id: 176, countryCode: 'tr', userName: 'tribundergi', displayName: 'Tribun Dergi', accountType: 'news_agency' as const, description: 'Spor dergisi' },

        // Germany
        { id: 8, countryCode: 'de', userName: 'Bundeskanzler', displayName: 'Bundeskanzler', accountType: 'government' as const, description: 'Federal Chancellor' },
        { id: 9, countryCode: 'de', userName: 'AusijirtigesAmt', displayName: 'Auswaertiges Amt', accountType: 'government' as const, description: 'Federal Foreign Office' },
        { id: 10, countryCode: 'de', userName: 'RegSprecher', displayName: 'Regierungssprecher', accountType: 'government' as const, description: 'Government Spokesperson' },
        { id: 11, countryCode: 'de', userName: 'taborakesschau', displayName: 'tagesschau', accountType: 'news_agency' as const, description: 'ARD public news' },
        { id: 12, countryCode: 'de', userName: 'ZDFheute', displayName: 'ZDFheute', accountType: 'news_agency' as const, description: 'ZDF public broadcaster' },
        { id: 13, countryCode: 'de', userName: 'dpa', displayName: 'dpa', accountType: 'news_agency' as const, description: 'Deutsche Presse-Agentur' },

        // United States
        { id: 14, countryCode: 'us', userName: 'POTUS', displayName: 'President of the United States', accountType: 'government' as const, description: 'US President official' },
        { id: 15, countryCode: 'us', userName: 'WhiteHouse', displayName: 'The White House', accountType: 'government' as const, description: 'White House official' },
        { id: 16, countryCode: 'us', userName: 'StateDept', displayName: 'Department of State', accountType: 'government' as const, description: 'US State Department' },
        { id: 17, countryCode: 'us', userName: 'AP', displayName: 'The Associated Press', accountType: 'news_agency' as const, description: 'AP wire service' },
        { id: 18, countryCode: 'us', userName: 'Reuters', displayName: 'Reuters', accountType: 'news_agency' as const, description: 'Reuters news wire' },
        { id: 19, countryCode: 'us', userName: 'ABC', displayName: 'ABC News', accountType: 'news_agency' as const, description: 'ABC News' },

        // United Kingdom
        { id: 20, countryCode: 'uk', userName: 'UKPrimeMinister', displayName: 'UK Prime Minister', accountType: 'government' as const, description: 'PM official' },
        { id: 21, countryCode: 'uk', userName: '10DowningStreet', displayName: '10 Downing Street', accountType: 'government' as const, description: 'PM office' },
        { id: 22, countryCode: 'uk', userName: 'FCDOGovUK', displayName: 'FCDO', accountType: 'government' as const, description: 'Foreign Commonwealth & Development Office' },
        { id: 23, countryCode: 'uk', userName: 'BBCNews', displayName: 'BBC News', accountType: 'news_agency' as const, description: 'BBC News (World)' },
        { id: 24, countryCode: 'uk', userName: 'SkyNews', displayName: 'Sky News', accountType: 'news_agency' as const, description: 'Sky News' },

        // France
        { id: 25, countryCode: 'fr', userName: 'EmmanuelMacron', displayName: 'Emmanuel Macron', accountType: 'government' as const, description: 'President of France' },
        { id: 26, countryCode: 'fr', userName: 'Elysee', displayName: 'Elysee', accountType: 'government' as const, description: 'French Presidency' },
        { id: 27, countryCode: 'fr', userName: 'francediplo', displayName: 'France Diplomatie', accountType: 'government' as const, description: 'Ministry of Foreign Affairs' },
        { id: 28, countryCode: 'fr', userName: 'gouvernementFR', displayName: 'Gouvernement', accountType: 'government' as const, description: 'French Government' },
        { id: 29, countryCode: 'fr', userName: 'AFP', displayName: 'AFP', accountType: 'news_agency' as const, description: 'Agence France-Presse' },
        { id: 30, countryCode: 'fr', userName: 'lemondefr', displayName: 'Le Monde', accountType: 'news_agency' as const, description: 'Le Monde newspaper' },

        // Spain
        { id: 31, countryCode: 'es', userName: 'saboraknchezcastejon', displayName: 'Pedro Sanchez', accountType: 'government' as const, description: 'President of the Government' },
        { id: 32, countryCode: 'es', userName: 'lamoncloa', displayName: 'La Moncloa', accountType: 'government' as const, description: 'Spanish Government' },
        { id: 33, countryCode: 'es', userName: 'MAECgob', displayName: 'MAEC', accountType: 'government' as const, description: 'Ministry of Foreign Affairs' },
        { id: 34, countryCode: 'es', userName: 'EFEnoticias', displayName: 'Agencia EFE', accountType: 'news_agency' as const, description: 'EFE national news agency' },
        { id: 35, countryCode: 'es', userName: 'el_pais', displayName: 'El Pais', accountType: 'news_agency' as const, description: 'El Pais newspaper' },

        // Italy
        { id: 36, countryCode: 'it', userName: 'GiorgiaMeloni', displayName: 'Giorgia Meloni', accountType: 'government' as const, description: 'Prime Minister of Italy' },
        { id: 37, countryCode: 'it', userName: 'PalazzoChigi', displayName: 'Palazzo Chigi', accountType: 'government' as const, description: 'Italian Government' },
        { id: 38, countryCode: 'it', userName: 'ItalyMFA', displayName: 'Italy MFA', accountType: 'government' as const, description: 'Ministry of Foreign Affairs' },
        { id: 39, countryCode: 'it', userName: 'Agenzia_Ansa', displayName: 'ANSA', accountType: 'news_agency' as const, description: 'ANSA news agency' },
        { id: 40, countryCode: 'it', userName: 'repubblica', displayName: 'la Repubblica', accountType: 'news_agency' as const, description: 'la Repubblica newspaper' },

        // Russia
        { id: 41, countryCode: 'ru', userName: 'KremlinRussia_E', displayName: 'President of Russia', accountType: 'government' as const, description: 'Kremlin English-language' },
        { id: 42, countryCode: 'ru', userName: 'mfa_russia', displayName: 'MFA Russia', accountType: 'government' as const, description: 'Ministry of Foreign Affairs (EN)' },
        { id: 43, countryCode: 'ru', userName: 'tass_agency', displayName: 'TASS', accountType: 'news_agency' as const, description: 'TASS Russian News Agency' },
    ]).onConflictDoNothing();
    console.log('✅ Twitter accounts seeded (or already exist)');

    console.log('🎉 Seeding completed!');
}

seed()
    .catch((error) => {
        console.error('❌ Seeding failed:', error);
        process.exit(1);
    })
    .then(() => {
        process.exit(0);
    });
